from protocolbuffers._ProtobufTypes import Message
from protocolbuffers._ProtobufTypes import RepeatedCompositeFieldContainer
from enum import IntEnum

from protocolbuffers.ResourceKey_pb2 import *
from protocolbuffers.Math_pb2 import *
from protocolbuffers.Consts_pb2 import *
from protocolbuffers.Localization_pb2 import *
from protocolbuffers.SimObjectAttributes_pb2 import *
from protocolbuffers.GameplaySaveData_pb2 import *
from protocolbuffers.Routing_pb2 import *
from protocolbuffers.Animation_pb2 import *
from protocolbuffers.FileSerialization_pb2 import *
from protocolbuffers.S4Common_pb2 import *
from protocolbuffers.Outfits_pb2 import *
from protocolbuffers.UI_pb2 import *
from protocolbuffers.Business_pb2 import *
from protocolbuffers.Kingdom_pb2 import *


class Operation(Message):
    class Type(IntEnum):
        OBJECT_DELETE: 'Operation.Type' = 1
        SET_TRANSFORM: 'Operation.Type' = 2
        SET_LOCATION: 'Operation.Type' = 3
        SET_MODEL: 'Operation.Type' = 4
        SET_RIG: 'Operation.Type' = 5
        ROUTE_CANCEL: 'Operation.Type' = 7
        SET_FOOTPRINT: 'Operation.Type' = 8
        ROUTE_UPDATE: 'Operation.Type' = 9
        FOCUS: 'Operation.Type' = 10
        FOCUS_NON_BLOCKING: 'Operation.Type' = 11
        SET_SCALE: 'Operation.Type' = 12
        SET_SLOT: 'Operation.Type' = 14
        SET_ACTOR_DATA: 'Operation.Type' = 15
        UI_UPDATE: 'Operation.Type' = 16
        SET_INTERACTABLE: 'Operation.Type' = 17
        SOUND_STOP: 'Operation.Type' = 18
        SET_SORT_ORDER: 'Operation.Type' = 19
        VFX_STOP: 'Operation.Type' = 20
        SET_SIM_ACTIVE: 'Operation.Type' = 21
        SET_SIM_OUTFIT: 'Operation.Type' = 22
        SET_TINT: 'Operation.Type' = 23
        SET_OPACITY: 'Operation.Type' = 24
        SET_GEOMETRY_STATE: 'Operation.Type' = 25
        SET_VISIBILITY: 'Operation.Type' = 26
        SET_MATERIAL_STATE: 'Operation.Type' = 27
        ARB_INITIAL_UPDATE: 'Operation.Type' = 28
        SET_AUDIO_EFFECTS: 'Operation.Type' = 29
        SET_VOICE_PITCH: 'Operation.Type' = 30
        SET_SKIN_TONE: 'Operation.Type' = 31
        OBJECT_REPLACE: 'Operation.Type' = 32
        SET_SIM_GAMEPLAY_FILTER_FX: 'Operation.Type' = 33
        ARB: 'Operation.Type' = 34
        FOLLOW_ROUTE: 'Operation.Type' = 35
        SOUND_START: 'Operation.Type' = 36
        VFX_START: 'Operation.Type' = 37
        ENABLE_PENDING_HEADLINE: 'Operation.Type' = 38
        DISABLE_PENDING_HEADLINE: 'Operation.Type' = 39
        SOCIAL_GROUP_UPDATE: 'Operation.Type' = 40
        OBJECT_CREATE: 'Operation.Type' = 41
        SOCIAL_GROUP_CREATE: 'Operation.Type' = 42
        SIM_INFO_CREATE: 'Operation.Type' = 43
        SOCIAL_GROUP_DELETE: 'Operation.Type' = 44
        SIM_INFO_DELETE: 'Operation.Type' = 45
        LOOT_PLUMBBOB: 'Operation.Type' = 46
        LOOT_PIP: 'Operation.Type' = 47
        SET_VOICE_ACTOR: 'Operation.Type' = 48
        SET_PHYSIQUE: 'Operation.Type' = 49
        CLIENT_CREATE: 'Operation.Type' = 50
        CLIENT_DELETE: 'Operation.Type' = 51
        SET_THUMBNAIL: 'Operation.Type' = 52
        ADD_BALLOON: 'Operation.Type' = 53
        RESLOT_PLUMBBOB: 'Operation.Type' = 54
        SET_FACIAL_ATTRIBUTES: 'Operation.Type' = 55
        SET_ACTIVE_RESOURCES: 'Operation.Type' = 56
        SET_UI_OBJECT_METADATA: 'Operation.Type' = 57
        SET_PARENT_TYPE: 'Operation.Type' = 58
        SIM_COMMODITY_UPDATE: 'Operation.Type' = 59
        SITUATION_START: 'Operation.Type' = 60
        SITUATION_END: 'Operation.Type' = 61
        SITUATION_SIM_JOB_CHANGED: 'Operation.Type' = 62
        SITUATION_SCORE_UPDATED: 'Operation.Type' = 63
        VIDEO_SET_PLAYLIST: 'Operation.Type' = 64
        SET_LIGHT_DIMMER: 'Operation.Type' = 65
        SET_CENSOR_STATE: 'Operation.Type' = 66
        FADE_OPACITY: 'Operation.Type' = 67
        PARTY_CREATE: 'Operation.Type' = 68
        PARTY_UPDATE: 'Operation.Type' = 69
        PARTY_DELETE: 'Operation.Type' = 70
        SET_MONEY: 'Operation.Type' = 71
        SET_PAINTING: 'Operation.Type' = 72
        HOUSEHOLD_CREATE: 'Operation.Type' = 73
        HOUSEHOLD_DELETE: 'Operation.Type' = 74
        SET_OBJECT_DEF_STATE_INDEX: 'Operation.Type' = 75
        SET_VALUE: 'Operation.Type' = 76
        SET_SIM_AGE: 'Operation.Type' = 77
        SET_SIM_AGE_PROGRESS: 'Operation.Type' = 78
        SET_SIM_GENDER: 'Operation.Type' = 79
        OBJECT_RESET: 'Operation.Type' = 80
        PARTY_KICKOUT: 'Operation.Type' = 81
        PARTY_TURN_UPDATE: 'Operation.Type' = 82
        SET_SIM_CURRENT_SKILL_ID: 'Operation.Type' = 83
        CHANGE_SIM_OUTFIT: 'Operation.Type' = 84
        SET_SIM_DEATH_TYPE: 'Operation.Type' = 85
        SET_GAME_TIME: 'Operation.Type' = 86
        SET_CAREER: 'Operation.Type' = 87
        SET_TRAITS: 'Operation.Type' = 88
        SET_SIM_SLEEP: 'Operation.Type' = 89
        SET_ACCOUNT_ID: 'Operation.Type' = 90
        SET_IS_NPC: 'Operation.Type' = 91
        SITUATION_GOALS_UPDATE: 'Operation.Type' = 92
        SITUATION_LEVEL_UPDATE: 'Operation.Type' = 93
        SITUATION_SIM_JOINED: 'Operation.Type' = 94
        SITUATION_SIM_LEFT: 'Operation.Type' = 95
        INTERACTION_PROGRESS_UPDATE: 'Operation.Type' = 96
        SET_SIM_GENETIC_DATA: 'Operation.Type' = 97
        SET_PRIMARY_ASPIRATION: 'Operation.Type' = 98
        SET_CURRENT_WHIMS: 'Operation.Type' = 99
        SET_WHIM_COMPLETE: 'Operation.Type' = 100
        SET_WHIM_BUCKS: 'Operation.Type' = 101
        SET_PREGNANCY_PROGRESS: 'Operation.Type' = 102
        TRAVEL_BRING_TO_ZONE: 'Operation.Type' = 103
        TRAVEL_SWITCH_TO_ZONE: 'Operation.Type' = 104
        UPDATE_FOOTPRINT_STATUS: 'Operation.Type' = 105
        COLLECTION_HOUSEHOLD_UPDATE: 'Operation.Type' = 106
        SET_FIRST_NAME: 'Operation.Type' = 107
        SET_LAST_NAME: 'Operation.Type' = 108
        SET_RELATED_OBJECTS: 'Operation.Type' = 110
        PRELOAD_SIM_OUTFIT: 'Operation.Type' = 111
        SIM_SKILL_PROGRESS: 'Operation.Type' = 112
        SIM_UPDATE: 'Operation.Type' = 113
        SIM_INTERACTION_QUEUE_VIEW_ADD: 'Operation.Type' = 114
        SIM_INTERACTIONS_ADD: 'Operation.Type' = 115
        SIM_INTERACTIONS_UPDATE: 'Operation.Type' = 116
        SIM_INTERACTIONS_REMOVE: 'Operation.Type' = 117
        SIM_INTERACTIONS_REMOVE_ALL: 'Operation.Type' = 118
        SIM_SERVER_RESPONSE_FAILED: 'Operation.Type' = 119
        SELECTABLE_SIMS_UPDATE: 'Operation.Type' = 120
        SIM_RELATIONSHIP_UPDATE: 'Operation.Type' = 121
        SIM_REL_HANDSHAKE_UPDATE: 'Operation.Type' = 122
        SIM_SIMOLEANS_UPDATE: 'Operation.Type' = 123
        SIM_INTERACTION_MOVE: 'Operation.Type' = 124
        SIM_INTERACTION_REPLACE: 'Operation.Type' = 125
        SIM_INTERACTION_QUICK_TIME_MIXER_UPDATE: 'Operation.Type' = 126
        SIM_INTERACTION_START: 'Operation.Type' = 127
        SIM_INTERACTION_END: 'Operation.Type' = 128
        SIM_INTERACTION_LIABILITY_UPDATE: 'Operation.Type' = 129
        SIM_CRAFTING_LIABILITY_UPDATE: 'Operation.Type' = 130
        PIE_MENU_CATEGORIES_STATIC_DATA_LIST: 'Operation.Type' = 131
        SIM_SKILL_UPDATE: 'Operation.Type' = 132
        SIM_BUFF_UPDATE: 'Operation.Type' = 133
        UI_DIALOG_SHOW: 'Operation.Type' = 134
        SIM_INTERACTION_TURN_START: 'Operation.Type' = 135
        SIM_MOOD_UPDATE: 'Operation.Type' = 136
        SIM_ASPIRATION_TRACKER_UPDATE: 'Operation.Type' = 137
        SIM_GOALS_STATUS_UPDATE: 'Operation.Type' = 138
        INVENTORY_UPDATE: 'Operation.Type' = 139
        SIM_INVENTORY_ITEM_UPDATE: 'Operation.Type' = 140
        SHOW_OBJECT_INVENTORY: 'Operation.Type' = 141
        PHONE_MENU_CREATE: 'Operation.Type' = 142
        UI_PHONE_RING: 'Operation.Type' = 143
        OBJECT_AUDIO_PLAYLIST_SKIP_TO_NEXT: 'Operation.Type' = 144
        ACCT_ACHIEVEMENT_TRACKER_UPDATE: 'Operation.Type' = 145
        ACCT_GOALS_STATUS_UPDATE: 'Operation.Type' = 146
        SIM_GENDER_PREFERENCE_UPDATE: 'Operation.Type' = 147
        TUTORIAL_TRIGGER: 'Operation.Type' = 148
        TUTORIAL_VIEWED_LIST: 'Operation.Type' = 149
        SIM_MEMORY_TRIGGER_UPDATE: 'Operation.Type' = 150
        SELECT_CAREER_UI: 'Operation.Type' = 151
        CAREER_SITUATION_ENABLE: 'Operation.Type' = 152
        SIM_COLLECTIBLE_ITEM_UPDATE: 'Operation.Type' = 153
        OBJECT_IS_INTERACTABLE: 'Operation.Type' = 154
        PIE_MENU_CREATE: 'Operation.Type' = 155
        INVENTORY_COUNT_UPDATE: 'Operation.Type' = 156
        TRAVEL_MENU_INFO: 'Operation.Type' = 157
        TRAVEL_MENU_SHOW: 'Operation.Type' = 158
        SIM_COMMODITY_PROGRESS_UPDATE: 'Operation.Type' = 159
        SOCIAL_CONTEXT_UPDATE: 'Operation.Type' = 160
        SET_AT_WORK_INFO: 'Operation.Type' = 161
        SIM_SATISFACTION_REWARDS: 'Operation.Type' = 162
        SET_FULL_NAME_KEY: 'Operation.Type' = 163
        SIM_TRANSFER_REQUEST: 'Operation.Type' = 164
        SET_WALLS_UP_OR_DOWN: 'Operation.Type' = 165
        UI_NOTIFICATION_SHOW: 'Operation.Type' = 166
        SET_CAN_LIVE_DRAG: 'Operation.Type' = 167
        LIVE_DRAG_START: 'Operation.Type' = 168
        LIVE_DRAG_END: 'Operation.Type' = 169
        LIVE_DRAG_CANCEL: 'Operation.Type' = 170
        SET_SINGED: 'Operation.Type' = 171
        INVENTORY_ITEM_UPDATE: 'Operation.Type' = 172
        SET_PHONE_SILENCE: 'Operation.Type' = 173
        LIFE_EVENT_SEND: 'Operation.Type' = 174
        OPEN_INVENTORY: 'Operation.Type' = 175
        SET_BABY_SKIN_TONE: 'Operation.Type' = 176
        MSG_SIM_PERSONALITY_ASSIGNMENT: 'Operation.Type' = 177
        SET_AWAY_ACTION: 'Operation.Type' = 178
        SET_LIGHT_COLOR: 'Operation.Type' = 179
        UI_LIGHT_COLOR_SHOW: 'Operation.Type' = 180
        SET_VOICE_EFFECT: 'Operation.Type' = 181
        SIM_RELATIONSHIP_DELETE: 'Operation.Type' = 182
        SET_OBJECT_DEFINITION_ID: 'Operation.Type' = 183
        SIM_RELATIVE_LOT_LOCATION: 'Operation.Type' = 184
        TUTORIAL_TIP_SATISFY: 'Operation.Type' = 185
        FOCUS_CAMERA: 'Operation.Type' = 186
        SET_SIM_AGE_PROGRESS_TOOLTIP_DATA: 'Operation.Type' = 187
        TRAVEL_VIEW_HOUSEHOLDS_INFO: 'Operation.Type' = 188
        SET_IS_GHOST: 'Operation.Type' = 189
        TRAVEL_GROUP_CREATE: 'Operation.Type' = 190
        TRAVEL_GROUP_DELETE: 'Operation.Type' = 191
        SET_GRUBBY: 'Operation.Type' = 192
        SET_OWNER_ID: 'Operation.Type' = 193
        SET_BUILDBUY_USE_FLAGS: 'Operation.Type' = 194
        SIM_BUFF_CLEAR_ALL: 'Operation.Type' = 195
        MOVE_HOUSEHOLD_INTO_LOT_FROM_GALLERY: 'Operation.Type' = 196
        TRAVEL_GROUP_LIST: 'Operation.Type' = 197
        SET_SIM_HEADLINE: 'Operation.Type' = 198
        SHOW_FAMILY_TREE: 'Operation.Type' = 199
        BUILD_BUY_LOCK_UNLOCK: 'Operation.Type' = 200
        SET_MULTICOLOR: 'Operation.Type' = 201
        VFX_SET_STATE: 'Operation.Type' = 202
        START_ENSEMBLE: 'Operation.Type' = 203
        UPDATE_ENSEMBLE: 'Operation.Type' = 204
        END_ENSEMBLE: 'Operation.Type' = 205
        SET_DISPLAY_NUMBER: 'Operation.Type' = 206
        SET_VFX_MASK: 'Operation.Type' = 207
        SET_OVERRIDE_DIALOG_PITCH: 'Operation.Type' = 208
        INIT_CAMERA_SHAKE: 'Operation.Type' = 209
        SET_CALL_TO_ACTION: 'Operation.Type' = 210
        PLUMBBOB_OVERRIDE_KEY: 'Operation.Type' = 211
        SIM_COMMODITY_LIST_UPDATE: 'Operation.Type' = 212
        SIM_SKILL_DELETE: 'Operation.Type' = 213
        MSG_INCREMENT_COMMUNITY_COLLECTABLE_COUNT: 'Operation.Type' = 214
        COMPOSITE_THUMBNAIL: 'Operation.Type' = 215
        SET_LINKED_SIMS: 'Operation.Type' = 216
        SET_VISIBILITY_FLAGS: 'Operation.Type' = 217
        FOCUS_CAMERA_ON_LOT: 'Operation.Type' = 218
        OVERRIDE_WALLS_UP: 'Operation.Type' = 219
        TIMED_ASPIRATIONS_UPDATE: 'Operation.Type' = 220
        DISPLAY_HEADLINE: 'Operation.Type' = 221
        COMPOSITE_IMAGES: 'Operation.Type' = 222
        SET_ACTOR_TYPE: 'Operation.Type' = 223
        SPLIT_HOUSEHOLD_DIALOG: 'Operation.Type' = 224
        SET_LOAN: 'Operation.Type' = 225
        SEND_UI_MESSAGE: 'Operation.Type' = 226
        SET_DYED: 'Operation.Type' = 227
        SHOW_BILLS_DIALOG: 'Operation.Type' = 228
        SET_ACTOR_STATE_MACHINE_PARAMS: 'Operation.Type' = 229
        UPDATE_FIND_CAREER_INTERACTION_AVAILABILITY: 'Operation.Type' = 230
        SET_EXCLUDE_VFX_MASK: 'Operation.Type' = 231
        SET_TRAIT_AT_RISK_STATE: 'Operation.Type' = 232
        TOGGLE_SIM_INFO_PANEL: 'Operation.Type' = 233
        REQUEST_OBJECT_THUMBNAIL: 'Operation.Type' = 234
        SET_PACKED_PRONOUNS: 'Operation.Type' = 235
        TRAIT_APPEARANCE_UPDATE: 'Operation.Type' = 236
        BOUND_OBJECT_UPDATE: 'Operation.Type' = 237
        DISPLAY_FAMILY_TREE: 'Operation.Type' = 238
        SET_OCCULT_TYPES: 'Operation.Type' = 250
        SET_CURRENT_OCCULT_TYPES: 'Operation.Type' = 251
        NOTEBOOK_VIEW: 'Operation.Type' = 252
        END_OF_WORKDAY: 'Operation.Type' = 253
        SET_MANNEQUIN_DATA: 'Operation.Type' = 254
        RETAIL_SUMMARY_DIALOG: 'Operation.Type' = 255
        INTERROGATION_PROGRESS_UPDATE: 'Operation.Type' = 256
        BREAK_THROUGH_MESSAGE: 'Operation.Type' = 257
        SET_MANNEQUIN_POSE: 'Operation.Type' = 258
        SET_FADEABLE_PART_OPACITY: 'Operation.Type' = 259
        FADE_FADEABLE_PART_OPACITY: 'Operation.Type' = 260
        CUSTOMIZABLE_OBJECT_DATA_LIST: 'Operation.Type' = 261
        TAKE_PHOTO: 'Operation.Type' = 262
        MAKE_MEMORY_FROM_PHOTO: 'Operation.Type' = 263
        SITUATION_TIME_UPDATE: 'Operation.Type' = 264
        SET_STANDIN_MODEL: 'Operation.Type' = 265
        SITUATION_CALLBACK_RESPONSE: 'Operation.Type' = 266
        SET_BUCK_FUNDS: 'Operation.Type' = 267
        SET_RETAIL_FUNDS: 'Operation.Type' = 268
        SET_RETAIL_DAILY_ITEMS_SOLD: 'Operation.Type' = 269
        SET_RETAIL_DAILY_OUTGOING_COSTS: 'Operation.Type' = 270
        SET_RETAIL_DAILY_NET_PROFIT: 'Operation.Type' = 271
        SET_RETAIL_STORE_OPEN: 'Operation.Type' = 272
        RETAIL_BALANCE_TRANSFER_DIALOG: 'Operation.Type' = 273
        PURCHASE_INTENT_UPDATE: 'Operation.Type' = 274
        SET_AURA: 'Operation.Type' = 275
        SET_LIGHT_MATERIAl_STATES: 'Operation.Type' = 276
        HOVERTIP_CREATED: 'Operation.Type' = 277
        SET_PROCEDURAL_ANIMATION_DATA: 'Operation.Type' = 278
        PROCEDURAL_CONTROL_ROTATE: 'Operation.Type' = 279
        SET_SKIN_TONE_VAL_SHIFT: 'Operation.Type' = 280
        SET_SIM_ATTACHMENT: 'Operation.Type' = 281
        DEVELOPMENTAL_MILESTONE_UPDATE: 'Operation.Type' = 282
        ALL_DEVELOPMENTAL_MILESTONES_UPDATE: 'Operation.Type' = 283
        SET_MESSY: 'Operation.Type' = 284
        UPDATE_SKEWER_THUMBNAIL: 'Operation.Type' = 285
        SET_HAUNTED_LIGHT: 'Operation.Type' = 290
        START_CLUB_GATHERING: 'Operation.Type' = 300
        UPDATE_CLUB_GATHERING: 'Operation.Type' = 301
        END_CLUB_GATHERING: 'Operation.Type' = 302
        SEND_CLUB_INFO: 'Operation.Type' = 303
        SEND_CLUB_BUILDING_INFO: 'Operation.Type' = 304
        SEND_CLUB_MEMBERSHIP_CRITERIA_VALIDATION: 'Operation.Type' = 305
        SEND_CLUB_VALIDATION: 'Operation.Type' = 306
        ASK_ABOUT_CLUBS_DIALOG: 'Operation.Type' = 307
        SEND_CLUB_INTERACTION_RULE_STATUS: 'Operation.Type' = 308
        SHOW_CLUB_INFO_UI: 'Operation.Type' = 309
        SOCIAL_GROUP_TARGET_UPDATE: 'Operation.Type' = 310
        DYNAMIC_SIGN_VIEW: 'Operation.Type' = 320
        OBJECT_RELATIONSHIP_UPDATE: 'Operation.Type' = 321
        DISPLAY_CAREER_TOOLTIP: 'Operation.Type' = 322
        UPDATE_FLIPBOOK: 'Operation.Type' = 350
        SET_SPECIES: 'Operation.Type' = 400
        SET_CUSTOM_TEXTURE: 'Operation.Type' = 401
        SET_PELT_LAYERS: 'Operation.Type' = 402
        SET_FOCUS_SCORE: 'Operation.Type' = 403
        SET_SCRATCHED_OVERLAY: 'Operation.Type' = 404
        SET_BREED_NAME: 'Operation.Type' = 405
        SET_BREED_NAME_KEY: 'Operation.Type' = 406
        SET_PLAYER_PROTECTED_STATUS: 'Operation.Type' = 407
        SET_PLAYED_STATUS: 'Operation.Type' = 408
        SET_HOUSEHOLD_NAME: 'Operation.Type' = 409
        SET_HOUSEHOLD_DESCRIPTION: 'Operation.Type' = 410
        SET_HOUSEHOLD_HOME_ZONE_ID: 'Operation.Type' = 411
        SET_HOUSEHOLD_HIDDEN: 'Operation.Type' = 412
        SITUATION_METER_UPDATE: 'Operation.Type' = 413
        SITUATION_ICON_UPDATE: 'Operation.Type' = 414
        VET_CLINIC_DATA_UPDATE: 'Operation.Type' = 415
        SET_HOUSEHOLD_SIMS: 'Operation.Type' = 416
        RESTAURANT_SHOW_MENU: 'Operation.Type' = 500
        BUSINESS_CUSTOMER_ADD: 'Operation.Type' = 501
        BUSINESS_CUSTOMER_REMOVE: 'Operation.Type' = 502
        BUSINESS_CUSTOMER_REVIEW_EVENT: 'Operation.Type' = 503
        BUSINESS_SUMMARY_DIALOG: 'Operation.Type' = 504
        SET_BUSINESS_DATA: 'Operation.Type' = 505
        BUSINESS_OPEN_UPDATE: 'Operation.Type' = 506
        BUSINESS_FUNDS_UPDATE: 'Operation.Type' = 507
        BUSINESS_PROFIT_UPDATE: 'Operation.Type' = 508
        RESTAURANT_DATA_UPDATE: 'Operation.Type' = 509
        REVIEW_DATA_UPDATE: 'Operation.Type' = 510
        BUSINESS_DAILY_ITEMS_SOLD_UPDATE: 'Operation.Type' = 511
        BUSINESS_DAILY_OUTGOING_COSTS_UPDATE: 'Operation.Type' = 512
        BUSINESS_DAILY_CUSTOMERS_SERVED_UPDATE: 'Operation.Type' = 513
        BUSINESS_MARKUP_DATA_UPDATE: 'Operation.Type' = 514
        BUSINESS_ADVERTISEMENT_DATA_UPDATE: 'Operation.Type' = 515
        BUSINESS_EMPLOYEE_MIN_REQUIREMENT_UPDATE: 'Operation.Type' = 516
        RANKED_STATISTIC_PROGRESS: 'Operation.Type' = 517
        HOUSEHOLD_UPDATE: 'Operation.Type' = 519
        LIFE_SKILL_UPDATE: 'Operation.Type' = 520
        LIFE_SKILL_DELETE: 'Operation.Type' = 521
        SIM_ALERT_UPDATE: 'Operation.Type' = 522
        HEARTBEAT: 'Operation.Type' = 523
        AWARENESS_CONFIGURE_AWARENESS: 'Operation.Type' = 600
        AWARENESS_CONFIGURE_NOTICEABLE: 'Operation.Type' = 601
        SEASON_WEATHER_INTERPOLATIONS: 'Operation.Type' = 700
        MSG_CALENDAR: 'Operation.Type' = 701
        MSG_CALENDAR_UPDATE: 'Operation.Type' = 702
        SEASON_UPDATE: 'Operation.Type' = 703
        HOLIDAY_INFO: 'Operation.Type' = 704
        UI_WEATHER_UPDATE: 'Operation.Type' = 705
        UI_WEATHER_FORECAST_UPDATE: 'Operation.Type' = 706
        CALENDAR_ALERT: 'Operation.Type' = 707
        SET_LOT_DECORATIONS: 'Operation.Type' = 708
        ACTIVE_HOLIDAY_INFO: 'Operation.Type' = 709
        RANKED_STATISTIC_RANK_CHANGED: 'Operation.Type' = 710
        SET_ALLOW_FAME: 'Operation.Type' = 711
        SET_ALLOW_REPUTATION: 'Operation.Type' = 712
        UPDATE_PREP_TASKS: 'Operation.Type' = 713
        AUDITION_UPDATE: 'Operation.Type' = 714
        PREFERENCES_UPDATE: 'Operation.Type' = 715
        SET_TAN_LEVEL: 'Operation.Type' = 800
        BOOK_VIEW: 'Operation.Type' = 900
        UNIVERSITY_ENROLLMENT_WIZARD: 'Operation.Type' = 950
        ORGANIZATION_UPDATE: 'Operation.Type' = 955
        ORGANIZATION_EVENT_UPDATE: 'Operation.Type' = 956
        OWNED_UNIVERSITY_HOUSING_LOAD: 'Operation.Type' = 975
        TRAVEL_LIVE_TO_NHD_TO_LIVE: 'Operation.Type' = 976
        COMMUNITY_POLICY_BOARD: 'Operation.Type' = 1000
        COMMUNITY_POLICY_ADD_POLICY: 'Operation.Type' = 1001
        CIVIC_POLICY_PANEL_UPDATE: 'Operation.Type' = 1002
        SET_PINWHEEL_SPIN_SPEED: 'Operation.Type' = 1003
        TOGGLE_CUSTOM_CAMERA: 'Operation.Type' = 1100
        UPDATE_GIG_BUDGET: 'Operation.Type' = 1110
        REQUEST_LIVE_EVENTS: 'Operation.Type' = 1150
        OPEN_TUTORIAL: 'Operation.Type' = 1160
        SET_VOICE_SUFFIX_OVERRIDES: 'Operation.Type' = 1200
        SET_FIRST_NAME_KEY: 'Operation.Type' = 1201
        SET_LAST_NAME_KEY: 'Operation.Type' = 1202
        CANCEL_FOCUS_CAMERA: 'Operation.Type' = 1203
        NOTIFY_NOTEBOOK_ENTRY_DISCOVERED: 'Operation.Type' = 1204
        SCENARIO_GOALS_UPDATE: 'Operation.Type' = 1205
        SCENARIO_END: 'Operation.Type' = 1206
        MOON_PHASE_UPDATE: 'Operation.Type' = 1207
        UI_LUNAR_EFFECT_TOOLTIP_UPDATE: 'Operation.Type' = 1208
        MOON_FORECAST_UPDATE: 'Operation.Type' = 1209
        CLAN_MEMBERSHIP_UPDATE: 'Operation.Type' = 1210
        CLAN_UPDATE: 'Operation.Type' = 1211
        SCENARIO_OUTCOME_DATA: 'Operation.Type' = 1212
        SHOW_SOCIAL_MEDIA_DIALOG: 'Operation.Type' = 1213
        SEND_PHONE_NOTIFICATION: 'Operation.Type' = 1214
        TOGGLE_PHONE_BADGE: 'Operation.Type' = 1215
        OPEN_INVENTORY_WITH_FILTERS: 'Operation.Type' = 1216
        SET_DISABLED_SLOTS: 'Operation.Type' = 1217
        GUIDANCE_TIP_RESULT: 'Operation.Type' = 1218
        SET_PUZZLE: 'Operation.Type' = 1219
        SHOW_LIFETIME_MILESTONES_PANEL: 'Operation.Type' = 1220
        HORSE_VALUE_UPDATE: 'Operation.Type' = 1221
        SHOW_HORSE_COMPETITION_SELECTOR: 'Operation.Type' = 1222
        SHOW_HORSE_COMPETITION_RESULTS: 'Operation.Type' = 1223
        REQUEST_DAYS_PLAYED: 'Operation.Type' = 1225
        REQUEST_COMPLETED_PIVOTAL_MOMENTS: 'Operation.Type' = 1226
        PIVOTAL_COMPLETED: 'Operation.Type' = 1227
        REQUEST_PIVOTAL_MOMENTS_LIVE_CHANGES: 'Operation.Type' = 1228
        SITUATION_SHOW_OUTCOME: 'Operation.Type' = 1229
        SWITCH_ACTIVE_HOUSEHOLD_CONTROL: 'Operation.Type' = 1235
        RENTAL_UNIT_DATA_UPDATE: 'Operation.Type' = 1236
        SHOW_RENTAL_UNIT_MANAGEMENT: 'Operation.Type' = 1237
        TENANT_APPLICATION_PANEL_UPDATE: 'Operation.Type' = 1238
        SHOW_MATCHMAKING_DIALOG: 'Operation.Type' = 1239
        GET_ACCOUNT_DATA_FOR_CURRENT_USER: 'Operation.Type' = 1258
        SET_ACCOUNT_DATA_FOR_CURRENT_USER: 'Operation.Type' = 1259
        REQUEST_LIVE_QUEST_EVENTS_DATA: 'Operation.Type' = 1260
        QUEST_GOAL_COMPLETE: 'Operation.Type' = 1261
        QUEST_COMPLETE: 'Operation.Type' = 1262
        SET_GHOST_COLOR: 'Operation.Type' = 1263
        SET_PACKED_PRONOUNS_KEY: 'Operation.Type' = 1264
        SET_UNFINISHED_BUSINESS_ASPIRATION: 'Operation.Type' = 1265
        SIM_UNFINISHED_BUSINESS_ASPIRATION_TRACKER_UPDATE: 'Operation.Type' = 1266
        GENERATE_MEMORIAL_PHOTO: 'Operation.Type' = 1267
        REINCARNATION_COUNT_UPDATE: 'Operation.Type' = 1268
        TRIGGER_UI_FLYAWAY: 'Operation.Type' = 1269
        GET_GROUPS_FOR_EXPERIMENTS: 'Operation.Type' = 1270
        SMALL_BUSINESS_DATA_UPDATE: 'Operation.Type' = 1271
        SIM_BUSINESS_DELETE: 'Operation.Type' = 1272
        UPDATE_BUSINESS_PRESETS: 'Operation.Type' = 1273
        SET_PARTS_CUSTOM_TATTOOS: 'Operation.Type' = 1274
        SET_BUSINESS_NAME_DESCRIPTION_KEY: 'Operation.Type' = 1275
        SET_NPC_BUSINESS_DATA: 'Operation.Type' = 1276
        SET_HOUSEHOLD_INVENTORY_REWARDS: 'Operation.Type' = 1277
        ADD_MINIMIZED_SITUATION: 'Operation.Type' = 1278
        REMOVE_MINIMIZED_SITUATION: 'Operation.Type' = 1279
        LUCK_UPDATE: 'Operation.Type' = 1280
        IS_GUIDANCE_TIP_COMPLETE: 'Operation.Type' = 1281
        SET_CALL_TO_ACTION_LOT: 'Operation.Type' = 1282
        CUSTOM_SCHEDULE_SET_CUSTOM_SCHEDULE: 'Operation.Type' = 1300
        CUSTOM_SCHEDULE_SET_CUSTOM_ASSIGNMENT: 'Operation.Type' = 1301
        CUSTOM_SCHEDULE_SET_CUSTOM_SET_SCHEDULE_LIST: 'Operation.Type' = 1302
        CUSTOM_SCHEDULE_SET_CUSTOM_SET_ASSIGNMENT_LIST: 'Operation.Type' = 1303
        CUSTOM_SCHEDULE_SET_CUSTOM_SET_MANNEQUIN_DATA: 'Operation.Type' = 1304
        SITUATION_UPDATE_ACTIVE_SCHEDULE: 'Operation.Type' = 1305
        MSG_SITUATION_GETAWAY_RULES: 'Operation.Type' = 1306
        SIM_SUGGESTED_ASPIRATION_UPDATE: 'Operation.Type' = 1307
        CHILDHOOD_INSPIRATION_COMPLETE_STATE_UPDATE: 'Operation.Type' = 1308
        CUSTOM_SCHEDULE_SET_AVAILABLE_SIMS: 'Operation.Type' = 1309
        SET_VISIBILITY_IMMEDIATE: 'Operation.Type' = 1310
        SET_RESIDENT_LIST: 'Operation.Type' = 1311
        KINGDOM_UPDATE: 'Operation.Type' = 1320
        SEND_DYNASTY_INFO: 'Operation.Type' = 1321
        KINGDOM_SEND_AVAILABLE_DECREES: 'Operation.Type' = 1322
        SET_PLUMBBOB_ENSEMBLE_TEXTURE: 'Operation.Type' = 1323
        SET_PLUMBBOB_ENSEMBLE_TINT: 'Operation.Type' = 1324
        SEND_SCANDAL_SECRET_INFO: 'Operation.Type' = 1325
        SET_DYNASTY_NAME_DESCRIPTION_KEY: 'Operation.Type' = 1326
        SHOW_SIM_COMPETITION_SELECTOR: 'Operation.Type' = 1327
        SHOW_SIM_COMPETITION_RESULTS: 'Operation.Type' = 1328
        KINGDOM_REQUEST_DEFAULT_PRONOUNS: 'Operation.Type' = 1329
        SET_ANCESTORS_DATA: 'Operation.Type' = 1330

    OBJECT_DELETE = Type.OBJECT_DELETE
    SET_TRANSFORM = Type.SET_TRANSFORM
    SET_LOCATION = Type.SET_LOCATION
    SET_MODEL = Type.SET_MODEL
    SET_RIG = Type.SET_RIG
    ROUTE_CANCEL = Type.ROUTE_CANCEL
    SET_FOOTPRINT = Type.SET_FOOTPRINT
    ROUTE_UPDATE = Type.ROUTE_UPDATE
    FOCUS = Type.FOCUS
    FOCUS_NON_BLOCKING = Type.FOCUS_NON_BLOCKING
    SET_SCALE = Type.SET_SCALE
    SET_SLOT = Type.SET_SLOT
    SET_ACTOR_DATA = Type.SET_ACTOR_DATA
    UI_UPDATE = Type.UI_UPDATE
    SET_INTERACTABLE = Type.SET_INTERACTABLE
    SOUND_STOP = Type.SOUND_STOP
    SET_SORT_ORDER = Type.SET_SORT_ORDER
    VFX_STOP = Type.VFX_STOP
    SET_SIM_ACTIVE = Type.SET_SIM_ACTIVE
    SET_SIM_OUTFIT = Type.SET_SIM_OUTFIT
    SET_TINT = Type.SET_TINT
    SET_OPACITY = Type.SET_OPACITY
    SET_GEOMETRY_STATE = Type.SET_GEOMETRY_STATE
    SET_VISIBILITY = Type.SET_VISIBILITY
    SET_MATERIAL_STATE = Type.SET_MATERIAL_STATE
    ARB_INITIAL_UPDATE = Type.ARB_INITIAL_UPDATE
    SET_AUDIO_EFFECTS = Type.SET_AUDIO_EFFECTS
    SET_VOICE_PITCH = Type.SET_VOICE_PITCH
    SET_SKIN_TONE = Type.SET_SKIN_TONE
    OBJECT_REPLACE = Type.OBJECT_REPLACE
    SET_SIM_GAMEPLAY_FILTER_FX = Type.SET_SIM_GAMEPLAY_FILTER_FX
    ARB = Type.ARB
    FOLLOW_ROUTE = Type.FOLLOW_ROUTE
    SOUND_START = Type.SOUND_START
    VFX_START = Type.VFX_START
    ENABLE_PENDING_HEADLINE = Type.ENABLE_PENDING_HEADLINE
    DISABLE_PENDING_HEADLINE = Type.DISABLE_PENDING_HEADLINE
    SOCIAL_GROUP_UPDATE = Type.SOCIAL_GROUP_UPDATE
    OBJECT_CREATE = Type.OBJECT_CREATE
    SOCIAL_GROUP_CREATE = Type.SOCIAL_GROUP_CREATE
    SIM_INFO_CREATE = Type.SIM_INFO_CREATE
    SOCIAL_GROUP_DELETE = Type.SOCIAL_GROUP_DELETE
    SIM_INFO_DELETE = Type.SIM_INFO_DELETE
    LOOT_PLUMBBOB = Type.LOOT_PLUMBBOB
    LOOT_PIP = Type.LOOT_PIP
    SET_VOICE_ACTOR = Type.SET_VOICE_ACTOR
    SET_PHYSIQUE = Type.SET_PHYSIQUE
    CLIENT_CREATE = Type.CLIENT_CREATE
    CLIENT_DELETE = Type.CLIENT_DELETE
    SET_THUMBNAIL = Type.SET_THUMBNAIL
    ADD_BALLOON = Type.ADD_BALLOON
    RESLOT_PLUMBBOB = Type.RESLOT_PLUMBBOB
    SET_FACIAL_ATTRIBUTES = Type.SET_FACIAL_ATTRIBUTES
    SET_ACTIVE_RESOURCES = Type.SET_ACTIVE_RESOURCES
    SET_UI_OBJECT_METADATA = Type.SET_UI_OBJECT_METADATA
    SET_PARENT_TYPE = Type.SET_PARENT_TYPE
    SIM_COMMODITY_UPDATE = Type.SIM_COMMODITY_UPDATE
    SITUATION_START = Type.SITUATION_START
    SITUATION_END = Type.SITUATION_END
    SITUATION_SIM_JOB_CHANGED = Type.SITUATION_SIM_JOB_CHANGED
    SITUATION_SCORE_UPDATED = Type.SITUATION_SCORE_UPDATED
    VIDEO_SET_PLAYLIST = Type.VIDEO_SET_PLAYLIST
    SET_LIGHT_DIMMER = Type.SET_LIGHT_DIMMER
    SET_CENSOR_STATE = Type.SET_CENSOR_STATE
    FADE_OPACITY = Type.FADE_OPACITY
    PARTY_CREATE = Type.PARTY_CREATE
    PARTY_UPDATE = Type.PARTY_UPDATE
    PARTY_DELETE = Type.PARTY_DELETE
    SET_MONEY = Type.SET_MONEY
    SET_PAINTING = Type.SET_PAINTING
    HOUSEHOLD_CREATE = Type.HOUSEHOLD_CREATE
    HOUSEHOLD_DELETE = Type.HOUSEHOLD_DELETE
    SET_OBJECT_DEF_STATE_INDEX = Type.SET_OBJECT_DEF_STATE_INDEX
    SET_VALUE = Type.SET_VALUE
    SET_SIM_AGE = Type.SET_SIM_AGE
    SET_SIM_AGE_PROGRESS = Type.SET_SIM_AGE_PROGRESS
    SET_SIM_GENDER = Type.SET_SIM_GENDER
    OBJECT_RESET = Type.OBJECT_RESET
    PARTY_KICKOUT = Type.PARTY_KICKOUT
    PARTY_TURN_UPDATE = Type.PARTY_TURN_UPDATE
    SET_SIM_CURRENT_SKILL_ID = Type.SET_SIM_CURRENT_SKILL_ID
    CHANGE_SIM_OUTFIT = Type.CHANGE_SIM_OUTFIT
    SET_SIM_DEATH_TYPE = Type.SET_SIM_DEATH_TYPE
    SET_GAME_TIME = Type.SET_GAME_TIME
    SET_CAREER = Type.SET_CAREER
    SET_TRAITS = Type.SET_TRAITS
    SET_SIM_SLEEP = Type.SET_SIM_SLEEP
    SET_ACCOUNT_ID = Type.SET_ACCOUNT_ID
    SET_IS_NPC = Type.SET_IS_NPC
    SITUATION_GOALS_UPDATE = Type.SITUATION_GOALS_UPDATE
    SITUATION_LEVEL_UPDATE = Type.SITUATION_LEVEL_UPDATE
    SITUATION_SIM_JOINED = Type.SITUATION_SIM_JOINED
    SITUATION_SIM_LEFT = Type.SITUATION_SIM_LEFT
    INTERACTION_PROGRESS_UPDATE = Type.INTERACTION_PROGRESS_UPDATE
    SET_SIM_GENETIC_DATA = Type.SET_SIM_GENETIC_DATA
    SET_PRIMARY_ASPIRATION = Type.SET_PRIMARY_ASPIRATION
    SET_CURRENT_WHIMS = Type.SET_CURRENT_WHIMS
    SET_WHIM_COMPLETE = Type.SET_WHIM_COMPLETE
    SET_WHIM_BUCKS = Type.SET_WHIM_BUCKS
    SET_PREGNANCY_PROGRESS = Type.SET_PREGNANCY_PROGRESS
    TRAVEL_BRING_TO_ZONE = Type.TRAVEL_BRING_TO_ZONE
    TRAVEL_SWITCH_TO_ZONE = Type.TRAVEL_SWITCH_TO_ZONE
    UPDATE_FOOTPRINT_STATUS = Type.UPDATE_FOOTPRINT_STATUS
    COLLECTION_HOUSEHOLD_UPDATE = Type.COLLECTION_HOUSEHOLD_UPDATE
    SET_FIRST_NAME = Type.SET_FIRST_NAME
    SET_LAST_NAME = Type.SET_LAST_NAME
    SET_RELATED_OBJECTS = Type.SET_RELATED_OBJECTS
    PRELOAD_SIM_OUTFIT = Type.PRELOAD_SIM_OUTFIT
    SIM_SKILL_PROGRESS = Type.SIM_SKILL_PROGRESS
    SIM_UPDATE = Type.SIM_UPDATE
    SIM_INTERACTION_QUEUE_VIEW_ADD = Type.SIM_INTERACTION_QUEUE_VIEW_ADD
    SIM_INTERACTIONS_ADD = Type.SIM_INTERACTIONS_ADD
    SIM_INTERACTIONS_UPDATE = Type.SIM_INTERACTIONS_UPDATE
    SIM_INTERACTIONS_REMOVE = Type.SIM_INTERACTIONS_REMOVE
    SIM_INTERACTIONS_REMOVE_ALL = Type.SIM_INTERACTIONS_REMOVE_ALL
    SIM_SERVER_RESPONSE_FAILED = Type.SIM_SERVER_RESPONSE_FAILED
    SELECTABLE_SIMS_UPDATE = Type.SELECTABLE_SIMS_UPDATE
    SIM_RELATIONSHIP_UPDATE = Type.SIM_RELATIONSHIP_UPDATE
    SIM_REL_HANDSHAKE_UPDATE = Type.SIM_REL_HANDSHAKE_UPDATE
    SIM_SIMOLEANS_UPDATE = Type.SIM_SIMOLEANS_UPDATE
    SIM_INTERACTION_MOVE = Type.SIM_INTERACTION_MOVE
    SIM_INTERACTION_REPLACE = Type.SIM_INTERACTION_REPLACE
    SIM_INTERACTION_QUICK_TIME_MIXER_UPDATE = Type.SIM_INTERACTION_QUICK_TIME_MIXER_UPDATE
    SIM_INTERACTION_START = Type.SIM_INTERACTION_START
    SIM_INTERACTION_END = Type.SIM_INTERACTION_END
    SIM_INTERACTION_LIABILITY_UPDATE = Type.SIM_INTERACTION_LIABILITY_UPDATE
    SIM_CRAFTING_LIABILITY_UPDATE = Type.SIM_CRAFTING_LIABILITY_UPDATE
    PIE_MENU_CATEGORIES_STATIC_DATA_LIST = Type.PIE_MENU_CATEGORIES_STATIC_DATA_LIST
    SIM_SKILL_UPDATE = Type.SIM_SKILL_UPDATE
    SIM_BUFF_UPDATE = Type.SIM_BUFF_UPDATE
    UI_DIALOG_SHOW = Type.UI_DIALOG_SHOW
    SIM_INTERACTION_TURN_START = Type.SIM_INTERACTION_TURN_START
    SIM_MOOD_UPDATE = Type.SIM_MOOD_UPDATE
    SIM_ASPIRATION_TRACKER_UPDATE = Type.SIM_ASPIRATION_TRACKER_UPDATE
    SIM_GOALS_STATUS_UPDATE = Type.SIM_GOALS_STATUS_UPDATE
    INVENTORY_UPDATE = Type.INVENTORY_UPDATE
    SIM_INVENTORY_ITEM_UPDATE = Type.SIM_INVENTORY_ITEM_UPDATE
    SHOW_OBJECT_INVENTORY = Type.SHOW_OBJECT_INVENTORY
    PHONE_MENU_CREATE = Type.PHONE_MENU_CREATE
    UI_PHONE_RING = Type.UI_PHONE_RING
    OBJECT_AUDIO_PLAYLIST_SKIP_TO_NEXT = Type.OBJECT_AUDIO_PLAYLIST_SKIP_TO_NEXT
    ACCT_ACHIEVEMENT_TRACKER_UPDATE = Type.ACCT_ACHIEVEMENT_TRACKER_UPDATE
    ACCT_GOALS_STATUS_UPDATE = Type.ACCT_GOALS_STATUS_UPDATE
    SIM_GENDER_PREFERENCE_UPDATE = Type.SIM_GENDER_PREFERENCE_UPDATE
    TUTORIAL_TRIGGER = Type.TUTORIAL_TRIGGER
    TUTORIAL_VIEWED_LIST = Type.TUTORIAL_VIEWED_LIST
    SIM_MEMORY_TRIGGER_UPDATE = Type.SIM_MEMORY_TRIGGER_UPDATE
    SELECT_CAREER_UI = Type.SELECT_CAREER_UI
    CAREER_SITUATION_ENABLE = Type.CAREER_SITUATION_ENABLE
    SIM_COLLECTIBLE_ITEM_UPDATE = Type.SIM_COLLECTIBLE_ITEM_UPDATE
    OBJECT_IS_INTERACTABLE = Type.OBJECT_IS_INTERACTABLE
    PIE_MENU_CREATE = Type.PIE_MENU_CREATE
    INVENTORY_COUNT_UPDATE = Type.INVENTORY_COUNT_UPDATE
    TRAVEL_MENU_INFO = Type.TRAVEL_MENU_INFO
    TRAVEL_MENU_SHOW = Type.TRAVEL_MENU_SHOW
    SIM_COMMODITY_PROGRESS_UPDATE = Type.SIM_COMMODITY_PROGRESS_UPDATE
    SOCIAL_CONTEXT_UPDATE = Type.SOCIAL_CONTEXT_UPDATE
    SET_AT_WORK_INFO = Type.SET_AT_WORK_INFO
    SIM_SATISFACTION_REWARDS = Type.SIM_SATISFACTION_REWARDS
    SET_FULL_NAME_KEY = Type.SET_FULL_NAME_KEY
    SIM_TRANSFER_REQUEST = Type.SIM_TRANSFER_REQUEST
    SET_WALLS_UP_OR_DOWN = Type.SET_WALLS_UP_OR_DOWN
    UI_NOTIFICATION_SHOW = Type.UI_NOTIFICATION_SHOW
    SET_CAN_LIVE_DRAG = Type.SET_CAN_LIVE_DRAG
    LIVE_DRAG_START = Type.LIVE_DRAG_START
    LIVE_DRAG_END = Type.LIVE_DRAG_END
    LIVE_DRAG_CANCEL = Type.LIVE_DRAG_CANCEL
    SET_SINGED = Type.SET_SINGED
    INVENTORY_ITEM_UPDATE = Type.INVENTORY_ITEM_UPDATE
    SET_PHONE_SILENCE = Type.SET_PHONE_SILENCE
    LIFE_EVENT_SEND = Type.LIFE_EVENT_SEND
    OPEN_INVENTORY = Type.OPEN_INVENTORY
    SET_BABY_SKIN_TONE = Type.SET_BABY_SKIN_TONE
    MSG_SIM_PERSONALITY_ASSIGNMENT = Type.MSG_SIM_PERSONALITY_ASSIGNMENT
    SET_AWAY_ACTION = Type.SET_AWAY_ACTION
    SET_LIGHT_COLOR = Type.SET_LIGHT_COLOR
    UI_LIGHT_COLOR_SHOW = Type.UI_LIGHT_COLOR_SHOW
    SET_VOICE_EFFECT = Type.SET_VOICE_EFFECT
    SIM_RELATIONSHIP_DELETE = Type.SIM_RELATIONSHIP_DELETE
    SET_OBJECT_DEFINITION_ID = Type.SET_OBJECT_DEFINITION_ID
    SIM_RELATIVE_LOT_LOCATION = Type.SIM_RELATIVE_LOT_LOCATION
    TUTORIAL_TIP_SATISFY = Type.TUTORIAL_TIP_SATISFY
    FOCUS_CAMERA = Type.FOCUS_CAMERA
    SET_SIM_AGE_PROGRESS_TOOLTIP_DATA = Type.SET_SIM_AGE_PROGRESS_TOOLTIP_DATA
    TRAVEL_VIEW_HOUSEHOLDS_INFO = Type.TRAVEL_VIEW_HOUSEHOLDS_INFO
    SET_IS_GHOST = Type.SET_IS_GHOST
    TRAVEL_GROUP_CREATE = Type.TRAVEL_GROUP_CREATE
    TRAVEL_GROUP_DELETE = Type.TRAVEL_GROUP_DELETE
    SET_GRUBBY = Type.SET_GRUBBY
    SET_OWNER_ID = Type.SET_OWNER_ID
    SET_BUILDBUY_USE_FLAGS = Type.SET_BUILDBUY_USE_FLAGS
    SIM_BUFF_CLEAR_ALL = Type.SIM_BUFF_CLEAR_ALL
    MOVE_HOUSEHOLD_INTO_LOT_FROM_GALLERY = Type.MOVE_HOUSEHOLD_INTO_LOT_FROM_GALLERY
    TRAVEL_GROUP_LIST = Type.TRAVEL_GROUP_LIST
    SET_SIM_HEADLINE = Type.SET_SIM_HEADLINE
    SHOW_FAMILY_TREE = Type.SHOW_FAMILY_TREE
    BUILD_BUY_LOCK_UNLOCK = Type.BUILD_BUY_LOCK_UNLOCK
    SET_MULTICOLOR = Type.SET_MULTICOLOR
    VFX_SET_STATE = Type.VFX_SET_STATE
    START_ENSEMBLE = Type.START_ENSEMBLE
    UPDATE_ENSEMBLE = Type.UPDATE_ENSEMBLE
    END_ENSEMBLE = Type.END_ENSEMBLE
    SET_DISPLAY_NUMBER = Type.SET_DISPLAY_NUMBER
    SET_VFX_MASK = Type.SET_VFX_MASK
    SET_OVERRIDE_DIALOG_PITCH = Type.SET_OVERRIDE_DIALOG_PITCH
    INIT_CAMERA_SHAKE = Type.INIT_CAMERA_SHAKE
    SET_CALL_TO_ACTION = Type.SET_CALL_TO_ACTION
    PLUMBBOB_OVERRIDE_KEY = Type.PLUMBBOB_OVERRIDE_KEY
    SIM_COMMODITY_LIST_UPDATE = Type.SIM_COMMODITY_LIST_UPDATE
    SIM_SKILL_DELETE = Type.SIM_SKILL_DELETE
    MSG_INCREMENT_COMMUNITY_COLLECTABLE_COUNT = Type.MSG_INCREMENT_COMMUNITY_COLLECTABLE_COUNT
    COMPOSITE_THUMBNAIL = Type.COMPOSITE_THUMBNAIL
    SET_LINKED_SIMS = Type.SET_LINKED_SIMS
    SET_VISIBILITY_FLAGS = Type.SET_VISIBILITY_FLAGS
    FOCUS_CAMERA_ON_LOT = Type.FOCUS_CAMERA_ON_LOT
    OVERRIDE_WALLS_UP = Type.OVERRIDE_WALLS_UP
    TIMED_ASPIRATIONS_UPDATE = Type.TIMED_ASPIRATIONS_UPDATE
    DISPLAY_HEADLINE = Type.DISPLAY_HEADLINE
    COMPOSITE_IMAGES = Type.COMPOSITE_IMAGES
    SET_ACTOR_TYPE = Type.SET_ACTOR_TYPE
    SPLIT_HOUSEHOLD_DIALOG = Type.SPLIT_HOUSEHOLD_DIALOG
    SET_LOAN = Type.SET_LOAN
    SEND_UI_MESSAGE = Type.SEND_UI_MESSAGE
    SET_DYED = Type.SET_DYED
    SHOW_BILLS_DIALOG = Type.SHOW_BILLS_DIALOG
    SET_ACTOR_STATE_MACHINE_PARAMS = Type.SET_ACTOR_STATE_MACHINE_PARAMS
    UPDATE_FIND_CAREER_INTERACTION_AVAILABILITY = Type.UPDATE_FIND_CAREER_INTERACTION_AVAILABILITY
    SET_EXCLUDE_VFX_MASK = Type.SET_EXCLUDE_VFX_MASK
    SET_TRAIT_AT_RISK_STATE = Type.SET_TRAIT_AT_RISK_STATE
    TOGGLE_SIM_INFO_PANEL = Type.TOGGLE_SIM_INFO_PANEL
    REQUEST_OBJECT_THUMBNAIL = Type.REQUEST_OBJECT_THUMBNAIL
    SET_PACKED_PRONOUNS = Type.SET_PACKED_PRONOUNS
    TRAIT_APPEARANCE_UPDATE = Type.TRAIT_APPEARANCE_UPDATE
    BOUND_OBJECT_UPDATE = Type.BOUND_OBJECT_UPDATE
    DISPLAY_FAMILY_TREE = Type.DISPLAY_FAMILY_TREE
    SET_OCCULT_TYPES = Type.SET_OCCULT_TYPES
    SET_CURRENT_OCCULT_TYPES = Type.SET_CURRENT_OCCULT_TYPES
    NOTEBOOK_VIEW = Type.NOTEBOOK_VIEW
    END_OF_WORKDAY = Type.END_OF_WORKDAY
    SET_MANNEQUIN_DATA = Type.SET_MANNEQUIN_DATA
    RETAIL_SUMMARY_DIALOG = Type.RETAIL_SUMMARY_DIALOG
    INTERROGATION_PROGRESS_UPDATE = Type.INTERROGATION_PROGRESS_UPDATE
    BREAK_THROUGH_MESSAGE = Type.BREAK_THROUGH_MESSAGE
    SET_MANNEQUIN_POSE = Type.SET_MANNEQUIN_POSE
    SET_FADEABLE_PART_OPACITY = Type.SET_FADEABLE_PART_OPACITY
    FADE_FADEABLE_PART_OPACITY = Type.FADE_FADEABLE_PART_OPACITY
    CUSTOMIZABLE_OBJECT_DATA_LIST = Type.CUSTOMIZABLE_OBJECT_DATA_LIST
    TAKE_PHOTO = Type.TAKE_PHOTO
    MAKE_MEMORY_FROM_PHOTO = Type.MAKE_MEMORY_FROM_PHOTO
    SITUATION_TIME_UPDATE = Type.SITUATION_TIME_UPDATE
    SET_STANDIN_MODEL = Type.SET_STANDIN_MODEL
    SITUATION_CALLBACK_RESPONSE = Type.SITUATION_CALLBACK_RESPONSE
    SET_BUCK_FUNDS = Type.SET_BUCK_FUNDS
    SET_RETAIL_FUNDS = Type.SET_RETAIL_FUNDS
    SET_RETAIL_DAILY_ITEMS_SOLD = Type.SET_RETAIL_DAILY_ITEMS_SOLD
    SET_RETAIL_DAILY_OUTGOING_COSTS = Type.SET_RETAIL_DAILY_OUTGOING_COSTS
    SET_RETAIL_DAILY_NET_PROFIT = Type.SET_RETAIL_DAILY_NET_PROFIT
    SET_RETAIL_STORE_OPEN = Type.SET_RETAIL_STORE_OPEN
    RETAIL_BALANCE_TRANSFER_DIALOG = Type.RETAIL_BALANCE_TRANSFER_DIALOG
    PURCHASE_INTENT_UPDATE = Type.PURCHASE_INTENT_UPDATE
    SET_AURA = Type.SET_AURA
    SET_LIGHT_MATERIAl_STATES = Type.SET_LIGHT_MATERIAl_STATES
    HOVERTIP_CREATED = Type.HOVERTIP_CREATED
    SET_PROCEDURAL_ANIMATION_DATA = Type.SET_PROCEDURAL_ANIMATION_DATA
    PROCEDURAL_CONTROL_ROTATE = Type.PROCEDURAL_CONTROL_ROTATE
    SET_SKIN_TONE_VAL_SHIFT = Type.SET_SKIN_TONE_VAL_SHIFT
    SET_SIM_ATTACHMENT = Type.SET_SIM_ATTACHMENT
    DEVELOPMENTAL_MILESTONE_UPDATE = Type.DEVELOPMENTAL_MILESTONE_UPDATE
    ALL_DEVELOPMENTAL_MILESTONES_UPDATE = Type.ALL_DEVELOPMENTAL_MILESTONES_UPDATE
    SET_MESSY = Type.SET_MESSY
    UPDATE_SKEWER_THUMBNAIL = Type.UPDATE_SKEWER_THUMBNAIL
    SET_HAUNTED_LIGHT = Type.SET_HAUNTED_LIGHT
    START_CLUB_GATHERING = Type.START_CLUB_GATHERING
    UPDATE_CLUB_GATHERING = Type.UPDATE_CLUB_GATHERING
    END_CLUB_GATHERING = Type.END_CLUB_GATHERING
    SEND_CLUB_INFO = Type.SEND_CLUB_INFO
    SEND_CLUB_BUILDING_INFO = Type.SEND_CLUB_BUILDING_INFO
    SEND_CLUB_MEMBERSHIP_CRITERIA_VALIDATION = Type.SEND_CLUB_MEMBERSHIP_CRITERIA_VALIDATION
    SEND_CLUB_VALIDATION = Type.SEND_CLUB_VALIDATION
    ASK_ABOUT_CLUBS_DIALOG = Type.ASK_ABOUT_CLUBS_DIALOG
    SEND_CLUB_INTERACTION_RULE_STATUS = Type.SEND_CLUB_INTERACTION_RULE_STATUS
    SHOW_CLUB_INFO_UI = Type.SHOW_CLUB_INFO_UI
    SOCIAL_GROUP_TARGET_UPDATE = Type.SOCIAL_GROUP_TARGET_UPDATE
    DYNAMIC_SIGN_VIEW = Type.DYNAMIC_SIGN_VIEW
    OBJECT_RELATIONSHIP_UPDATE = Type.OBJECT_RELATIONSHIP_UPDATE
    DISPLAY_CAREER_TOOLTIP = Type.DISPLAY_CAREER_TOOLTIP
    UPDATE_FLIPBOOK = Type.UPDATE_FLIPBOOK
    SET_SPECIES = Type.SET_SPECIES
    SET_CUSTOM_TEXTURE = Type.SET_CUSTOM_TEXTURE
    SET_PELT_LAYERS = Type.SET_PELT_LAYERS
    SET_FOCUS_SCORE = Type.SET_FOCUS_SCORE
    SET_SCRATCHED_OVERLAY = Type.SET_SCRATCHED_OVERLAY
    SET_BREED_NAME = Type.SET_BREED_NAME
    SET_BREED_NAME_KEY = Type.SET_BREED_NAME_KEY
    SET_PLAYER_PROTECTED_STATUS = Type.SET_PLAYER_PROTECTED_STATUS
    SET_PLAYED_STATUS = Type.SET_PLAYED_STATUS
    SET_HOUSEHOLD_NAME = Type.SET_HOUSEHOLD_NAME
    SET_HOUSEHOLD_DESCRIPTION = Type.SET_HOUSEHOLD_DESCRIPTION
    SET_HOUSEHOLD_HOME_ZONE_ID = Type.SET_HOUSEHOLD_HOME_ZONE_ID
    SET_HOUSEHOLD_HIDDEN = Type.SET_HOUSEHOLD_HIDDEN
    SITUATION_METER_UPDATE = Type.SITUATION_METER_UPDATE
    SITUATION_ICON_UPDATE = Type.SITUATION_ICON_UPDATE
    VET_CLINIC_DATA_UPDATE = Type.VET_CLINIC_DATA_UPDATE
    SET_HOUSEHOLD_SIMS = Type.SET_HOUSEHOLD_SIMS
    RESTAURANT_SHOW_MENU = Type.RESTAURANT_SHOW_MENU
    BUSINESS_CUSTOMER_ADD = Type.BUSINESS_CUSTOMER_ADD
    BUSINESS_CUSTOMER_REMOVE = Type.BUSINESS_CUSTOMER_REMOVE
    BUSINESS_CUSTOMER_REVIEW_EVENT = Type.BUSINESS_CUSTOMER_REVIEW_EVENT
    BUSINESS_SUMMARY_DIALOG = Type.BUSINESS_SUMMARY_DIALOG
    SET_BUSINESS_DATA = Type.SET_BUSINESS_DATA
    BUSINESS_OPEN_UPDATE = Type.BUSINESS_OPEN_UPDATE
    BUSINESS_FUNDS_UPDATE = Type.BUSINESS_FUNDS_UPDATE
    BUSINESS_PROFIT_UPDATE = Type.BUSINESS_PROFIT_UPDATE
    RESTAURANT_DATA_UPDATE = Type.RESTAURANT_DATA_UPDATE
    REVIEW_DATA_UPDATE = Type.REVIEW_DATA_UPDATE
    BUSINESS_DAILY_ITEMS_SOLD_UPDATE = Type.BUSINESS_DAILY_ITEMS_SOLD_UPDATE
    BUSINESS_DAILY_OUTGOING_COSTS_UPDATE = Type.BUSINESS_DAILY_OUTGOING_COSTS_UPDATE
    BUSINESS_DAILY_CUSTOMERS_SERVED_UPDATE = Type.BUSINESS_DAILY_CUSTOMERS_SERVED_UPDATE
    BUSINESS_MARKUP_DATA_UPDATE = Type.BUSINESS_MARKUP_DATA_UPDATE
    BUSINESS_ADVERTISEMENT_DATA_UPDATE = Type.BUSINESS_ADVERTISEMENT_DATA_UPDATE
    BUSINESS_EMPLOYEE_MIN_REQUIREMENT_UPDATE = Type.BUSINESS_EMPLOYEE_MIN_REQUIREMENT_UPDATE
    RANKED_STATISTIC_PROGRESS = Type.RANKED_STATISTIC_PROGRESS
    HOUSEHOLD_UPDATE = Type.HOUSEHOLD_UPDATE
    LIFE_SKILL_UPDATE = Type.LIFE_SKILL_UPDATE
    LIFE_SKILL_DELETE = Type.LIFE_SKILL_DELETE
    SIM_ALERT_UPDATE = Type.SIM_ALERT_UPDATE
    HEARTBEAT = Type.HEARTBEAT
    AWARENESS_CONFIGURE_AWARENESS = Type.AWARENESS_CONFIGURE_AWARENESS
    AWARENESS_CONFIGURE_NOTICEABLE = Type.AWARENESS_CONFIGURE_NOTICEABLE
    SEASON_WEATHER_INTERPOLATIONS = Type.SEASON_WEATHER_INTERPOLATIONS
    MSG_CALENDAR = Type.MSG_CALENDAR
    MSG_CALENDAR_UPDATE = Type.MSG_CALENDAR_UPDATE
    SEASON_UPDATE = Type.SEASON_UPDATE
    HOLIDAY_INFO = Type.HOLIDAY_INFO
    UI_WEATHER_UPDATE = Type.UI_WEATHER_UPDATE
    UI_WEATHER_FORECAST_UPDATE = Type.UI_WEATHER_FORECAST_UPDATE
    CALENDAR_ALERT = Type.CALENDAR_ALERT
    SET_LOT_DECORATIONS = Type.SET_LOT_DECORATIONS
    ACTIVE_HOLIDAY_INFO = Type.ACTIVE_HOLIDAY_INFO
    RANKED_STATISTIC_RANK_CHANGED = Type.RANKED_STATISTIC_RANK_CHANGED
    SET_ALLOW_FAME = Type.SET_ALLOW_FAME
    SET_ALLOW_REPUTATION = Type.SET_ALLOW_REPUTATION
    UPDATE_PREP_TASKS = Type.UPDATE_PREP_TASKS
    AUDITION_UPDATE = Type.AUDITION_UPDATE
    PREFERENCES_UPDATE = Type.PREFERENCES_UPDATE
    SET_TAN_LEVEL = Type.SET_TAN_LEVEL
    BOOK_VIEW = Type.BOOK_VIEW
    UNIVERSITY_ENROLLMENT_WIZARD = Type.UNIVERSITY_ENROLLMENT_WIZARD
    ORGANIZATION_UPDATE = Type.ORGANIZATION_UPDATE
    ORGANIZATION_EVENT_UPDATE = Type.ORGANIZATION_EVENT_UPDATE
    OWNED_UNIVERSITY_HOUSING_LOAD = Type.OWNED_UNIVERSITY_HOUSING_LOAD
    TRAVEL_LIVE_TO_NHD_TO_LIVE = Type.TRAVEL_LIVE_TO_NHD_TO_LIVE
    COMMUNITY_POLICY_BOARD = Type.COMMUNITY_POLICY_BOARD
    COMMUNITY_POLICY_ADD_POLICY = Type.COMMUNITY_POLICY_ADD_POLICY
    CIVIC_POLICY_PANEL_UPDATE = Type.CIVIC_POLICY_PANEL_UPDATE
    SET_PINWHEEL_SPIN_SPEED = Type.SET_PINWHEEL_SPIN_SPEED
    TOGGLE_CUSTOM_CAMERA = Type.TOGGLE_CUSTOM_CAMERA
    UPDATE_GIG_BUDGET = Type.UPDATE_GIG_BUDGET
    REQUEST_LIVE_EVENTS = Type.REQUEST_LIVE_EVENTS
    OPEN_TUTORIAL = Type.OPEN_TUTORIAL
    SET_VOICE_SUFFIX_OVERRIDES = Type.SET_VOICE_SUFFIX_OVERRIDES
    SET_FIRST_NAME_KEY = Type.SET_FIRST_NAME_KEY
    SET_LAST_NAME_KEY = Type.SET_LAST_NAME_KEY
    CANCEL_FOCUS_CAMERA = Type.CANCEL_FOCUS_CAMERA
    NOTIFY_NOTEBOOK_ENTRY_DISCOVERED = Type.NOTIFY_NOTEBOOK_ENTRY_DISCOVERED
    SCENARIO_GOALS_UPDATE = Type.SCENARIO_GOALS_UPDATE
    SCENARIO_END = Type.SCENARIO_END
    MOON_PHASE_UPDATE = Type.MOON_PHASE_UPDATE
    UI_LUNAR_EFFECT_TOOLTIP_UPDATE = Type.UI_LUNAR_EFFECT_TOOLTIP_UPDATE
    MOON_FORECAST_UPDATE = Type.MOON_FORECAST_UPDATE
    CLAN_MEMBERSHIP_UPDATE = Type.CLAN_MEMBERSHIP_UPDATE
    CLAN_UPDATE = Type.CLAN_UPDATE
    SCENARIO_OUTCOME_DATA = Type.SCENARIO_OUTCOME_DATA
    SHOW_SOCIAL_MEDIA_DIALOG = Type.SHOW_SOCIAL_MEDIA_DIALOG
    SEND_PHONE_NOTIFICATION = Type.SEND_PHONE_NOTIFICATION
    TOGGLE_PHONE_BADGE = Type.TOGGLE_PHONE_BADGE
    OPEN_INVENTORY_WITH_FILTERS = Type.OPEN_INVENTORY_WITH_FILTERS
    SET_DISABLED_SLOTS = Type.SET_DISABLED_SLOTS
    GUIDANCE_TIP_RESULT = Type.GUIDANCE_TIP_RESULT
    SET_PUZZLE = Type.SET_PUZZLE
    SHOW_LIFETIME_MILESTONES_PANEL = Type.SHOW_LIFETIME_MILESTONES_PANEL
    HORSE_VALUE_UPDATE = Type.HORSE_VALUE_UPDATE
    SHOW_HORSE_COMPETITION_SELECTOR = Type.SHOW_HORSE_COMPETITION_SELECTOR
    SHOW_HORSE_COMPETITION_RESULTS = Type.SHOW_HORSE_COMPETITION_RESULTS
    REQUEST_DAYS_PLAYED = Type.REQUEST_DAYS_PLAYED
    REQUEST_COMPLETED_PIVOTAL_MOMENTS = Type.REQUEST_COMPLETED_PIVOTAL_MOMENTS
    PIVOTAL_COMPLETED = Type.PIVOTAL_COMPLETED
    REQUEST_PIVOTAL_MOMENTS_LIVE_CHANGES = Type.REQUEST_PIVOTAL_MOMENTS_LIVE_CHANGES
    SITUATION_SHOW_OUTCOME = Type.SITUATION_SHOW_OUTCOME
    SWITCH_ACTIVE_HOUSEHOLD_CONTROL = Type.SWITCH_ACTIVE_HOUSEHOLD_CONTROL
    RENTAL_UNIT_DATA_UPDATE = Type.RENTAL_UNIT_DATA_UPDATE
    SHOW_RENTAL_UNIT_MANAGEMENT = Type.SHOW_RENTAL_UNIT_MANAGEMENT
    TENANT_APPLICATION_PANEL_UPDATE = Type.TENANT_APPLICATION_PANEL_UPDATE
    SHOW_MATCHMAKING_DIALOG = Type.SHOW_MATCHMAKING_DIALOG
    GET_ACCOUNT_DATA_FOR_CURRENT_USER = Type.GET_ACCOUNT_DATA_FOR_CURRENT_USER
    SET_ACCOUNT_DATA_FOR_CURRENT_USER = Type.SET_ACCOUNT_DATA_FOR_CURRENT_USER
    REQUEST_LIVE_QUEST_EVENTS_DATA = Type.REQUEST_LIVE_QUEST_EVENTS_DATA
    QUEST_GOAL_COMPLETE = Type.QUEST_GOAL_COMPLETE
    QUEST_COMPLETE = Type.QUEST_COMPLETE
    SET_GHOST_COLOR = Type.SET_GHOST_COLOR
    SET_PACKED_PRONOUNS_KEY = Type.SET_PACKED_PRONOUNS_KEY
    SET_UNFINISHED_BUSINESS_ASPIRATION = Type.SET_UNFINISHED_BUSINESS_ASPIRATION
    SIM_UNFINISHED_BUSINESS_ASPIRATION_TRACKER_UPDATE = Type.SIM_UNFINISHED_BUSINESS_ASPIRATION_TRACKER_UPDATE
    GENERATE_MEMORIAL_PHOTO = Type.GENERATE_MEMORIAL_PHOTO
    REINCARNATION_COUNT_UPDATE = Type.REINCARNATION_COUNT_UPDATE
    TRIGGER_UI_FLYAWAY = Type.TRIGGER_UI_FLYAWAY
    GET_GROUPS_FOR_EXPERIMENTS = Type.GET_GROUPS_FOR_EXPERIMENTS
    SMALL_BUSINESS_DATA_UPDATE = Type.SMALL_BUSINESS_DATA_UPDATE
    SIM_BUSINESS_DELETE = Type.SIM_BUSINESS_DELETE
    UPDATE_BUSINESS_PRESETS = Type.UPDATE_BUSINESS_PRESETS
    SET_PARTS_CUSTOM_TATTOOS = Type.SET_PARTS_CUSTOM_TATTOOS
    SET_BUSINESS_NAME_DESCRIPTION_KEY = Type.SET_BUSINESS_NAME_DESCRIPTION_KEY
    SET_NPC_BUSINESS_DATA = Type.SET_NPC_BUSINESS_DATA
    SET_HOUSEHOLD_INVENTORY_REWARDS = Type.SET_HOUSEHOLD_INVENTORY_REWARDS
    ADD_MINIMIZED_SITUATION = Type.ADD_MINIMIZED_SITUATION
    REMOVE_MINIMIZED_SITUATION = Type.REMOVE_MINIMIZED_SITUATION
    LUCK_UPDATE = Type.LUCK_UPDATE
    IS_GUIDANCE_TIP_COMPLETE = Type.IS_GUIDANCE_TIP_COMPLETE
    SET_CALL_TO_ACTION_LOT = Type.SET_CALL_TO_ACTION_LOT
    CUSTOM_SCHEDULE_SET_CUSTOM_SCHEDULE = Type.CUSTOM_SCHEDULE_SET_CUSTOM_SCHEDULE
    CUSTOM_SCHEDULE_SET_CUSTOM_ASSIGNMENT = Type.CUSTOM_SCHEDULE_SET_CUSTOM_ASSIGNMENT
    CUSTOM_SCHEDULE_SET_CUSTOM_SET_SCHEDULE_LIST = Type.CUSTOM_SCHEDULE_SET_CUSTOM_SET_SCHEDULE_LIST
    CUSTOM_SCHEDULE_SET_CUSTOM_SET_ASSIGNMENT_LIST = Type.CUSTOM_SCHEDULE_SET_CUSTOM_SET_ASSIGNMENT_LIST
    CUSTOM_SCHEDULE_SET_CUSTOM_SET_MANNEQUIN_DATA = Type.CUSTOM_SCHEDULE_SET_CUSTOM_SET_MANNEQUIN_DATA
    SITUATION_UPDATE_ACTIVE_SCHEDULE = Type.SITUATION_UPDATE_ACTIVE_SCHEDULE
    MSG_SITUATION_GETAWAY_RULES = Type.MSG_SITUATION_GETAWAY_RULES
    SIM_SUGGESTED_ASPIRATION_UPDATE = Type.SIM_SUGGESTED_ASPIRATION_UPDATE
    CHILDHOOD_INSPIRATION_COMPLETE_STATE_UPDATE = Type.CHILDHOOD_INSPIRATION_COMPLETE_STATE_UPDATE
    CUSTOM_SCHEDULE_SET_AVAILABLE_SIMS = Type.CUSTOM_SCHEDULE_SET_AVAILABLE_SIMS
    SET_VISIBILITY_IMMEDIATE = Type.SET_VISIBILITY_IMMEDIATE
    SET_RESIDENT_LIST = Type.SET_RESIDENT_LIST
    KINGDOM_UPDATE = Type.KINGDOM_UPDATE
    SEND_DYNASTY_INFO = Type.SEND_DYNASTY_INFO
    KINGDOM_SEND_AVAILABLE_DECREES = Type.KINGDOM_SEND_AVAILABLE_DECREES
    SET_PLUMBBOB_ENSEMBLE_TEXTURE = Type.SET_PLUMBBOB_ENSEMBLE_TEXTURE
    SET_PLUMBBOB_ENSEMBLE_TINT = Type.SET_PLUMBBOB_ENSEMBLE_TINT
    SEND_SCANDAL_SECRET_INFO = Type.SEND_SCANDAL_SECRET_INFO
    SET_DYNASTY_NAME_DESCRIPTION_KEY = Type.SET_DYNASTY_NAME_DESCRIPTION_KEY
    SHOW_SIM_COMPETITION_SELECTOR = Type.SHOW_SIM_COMPETITION_SELECTOR
    SHOW_SIM_COMPETITION_RESULTS = Type.SHOW_SIM_COMPETITION_RESULTS
    KINGDOM_REQUEST_DEFAULT_PRONOUNS = Type.KINGDOM_REQUEST_DEFAULT_PRONOUNS
    SET_ANCESTORS_DATA = Type.SET_ANCESTORS_DATA

    # __init__
    type: 'Operation.Type'
    data: 'bytes'
    data_context: 'MessageTypes'
    primary_channel_mask_override: 'int'  # fixed uint32
    additional_channels: 'RepeatedCompositeFieldContainer[OperationChannel]'


class OperationList(Message):
    # __init__
    operations: 'RepeatedCompositeFieldContainer[Operation]'


class ObjectCreate(Message):
    # __init__
    components: 'RepeatedCompositeFieldContainer[int]'  # uint32
    operation_list: 'OperationList'
    def_id: 'int'  # uint64
    visible_to_automation: 'bool'
    notify_on_load: 'bool'


class ObjectReplace(Message):
    # __init__
    replacement_id: 'int'  # fixed uint64


class ObjectDelete(Message):
    # __init__
    fade_duration: 'float'  # float32


class ObjectReset(Message):
    # __init__
    object_id: 'int'  # uint64


class SocialGroupCreate(Message):
    # __init__
    operation_list: 'OperationList'


class SocialGroupUpdate(Message):
    class SocialGroupMember():
        # __init__
        sim_id: 'int'  # fixed uint64
        social_context_bit_id: 'int'  # fixed uint64

    # __init__
    members: 'RepeatedCompositeFieldContainer[SocialGroupUpdate.SocialGroupMember]'
    sim_id: 'int'  # fixed uint64
    social_context_bit_id: 'int'  # fixed uint64


class SocialGroupTargetUpdate(Message):
    # __init__
    sim_id: 'int'  # fixed uint64
    target_id: 'int'  # fixed uint64


class StartClubGathering(Message):
    # __init__
    club_id: 'int'  # uint64


class UpdateClubGathering(Message):
    class UpdateType(IntEnum):
        ADD_MEMBER: 'UpdateClubGathering.UpdateType' = 0
        REMOVE_MEMBER: 'UpdateClubGathering.UpdateType' = 1

    ADD_MEMBER = UpdateType.ADD_MEMBER
    REMOVE_MEMBER = UpdateType.REMOVE_MEMBER

    # __init__
    club_update_type: 'UpdateClubGathering.UpdateType'
    club_id: 'int'  # uint64
    member_id: 'int'  # uint64


class EndClubGathering(Message):
    # __init__
    club_id: 'int'  # uint64


class ClubInfo(Message):
    class ClubMessageType(IntEnum):
        ADD: 'ClubInfo.ClubMessageType' = 0
        REMOVE: 'ClubInfo.ClubMessageType' = 1
        UPDATE: 'ClubInfo.ClubMessageType' = 2

    ADD = ClubMessageType.ADD
    REMOVE = ClubMessageType.REMOVE
    UPDATE = ClubMessageType.UPDATE

    # __init__
    message_type: 'ClubInfo.ClubMessageType'
    clubs: 'RepeatedCompositeFieldContainer[Club]'


class ClubMembershipCriteriaValidation(Message):
    class FailureInfo():
        # __init__
        failed_sim_id: 'int'  # uint64
        failed_criteria_ids: 'RepeatedCompositeFieldContainer[int]'  # uint32

    # __init__
    failure_infos: 'RepeatedCompositeFieldContainer[ClubMembershipCriteriaValidation.FailureInfo]'
    failed_sim_id: 'int'  # uint64
    failed_criteria_ids: 'RepeatedCompositeFieldContainer[int]'  # uint32


class ClubValidation(Message):
    # __init__
    failed_sim_id: 'int'  # uint64
    failed_club_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64


class AskAboutClubsDialog(Message):
    # __init__
    sim_id: 'int'  # uint64
    club_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    show_orgs: 'bool'


class PartyMember(Message):
    # __init__
    sim_id: 'int'  # uint64
    brb_sim_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64


class PartyCreate(Message):
    # __init__
    operation_list: 'OperationList'


class PartyUpdate(Message):
    # __init__
    party_members: 'RepeatedCompositeFieldContainer[PartyMember]'


class PartyTurnUpdate(Message):
    # __init__
    active_sim_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64


class PartyKickout(Message):
    # __init__
    initiator_sim_id: 'int'  # uint64
    receiver_sim_id: 'int'  # uint64


class SimInfoCreate(Message):
    # __init__
    operation_list: 'OperationList'


class ClientCreate(Message):
    # __init__
    operation_list: 'OperationList'
    account_id: 'int'  # uint64
    household_id: 'int'  # uint64
    is_active: 'bool'


class SetOwnerID(Message):
    # __init__
    household_id: 'int'  # fixed uint64


class SetLocation(Message):
    # __init__
    transform: 'Transform'
    level: 'int'  # int32
    parent_id: 'int'  # uint64
    joint_name_hash: 'int'  # uint32
    slot_hash: 'int'  # uint32
    surface_id: 'SurfaceId'
    surface_object_id: 'int'  # uint64


class SetModel(Message):
    # __init__
    key: 'ResourceKey'
    variant_id: 'int'  # uint32


class SetRig(Message):
    # __init__
    key: 'ResourceKey'


class SetVoicePitch(Message):
    # __init__
    voice_pitch: 'float'  # float32


class SetSkinTone(Message):
    # __init__
    skin_tone: 'int'  # uint64


class SetSkinToneValShift(Message):
    # __init__
    skin_tone_val_shift: 'float'  # float32


class SetSimAttachment(Message):
    class AttachOption(IntEnum):
        ATTACH: 'SetSimAttachment.AttachOption' = 0
        DETACH: 'SetSimAttachment.AttachOption' = 1
        PREBUILD: 'SetSimAttachment.AttachOption' = 2

    ATTACH = AttachOption.ATTACH
    DETACH = AttachOption.DETACH
    PREBUILD = AttachOption.PREBUILD

    # __init__
    attachment_id: 'int'  # uint64
    attach_option: 'SetSimAttachment.AttachOption'
    infant_id: 'int'  # fixed uint64
    is_wing: 'bool'


class SetPeltLayers(Message):
    # __init__
    pelt_layers: 'PeltLayerDataList'


class SetCustomTexture(Message):
    # __init__
    custom_texture: 'int'  # uint64


class SetVoiceActor(Message):
    # __init__
    voice_actor: 'int'  # uint32


class SetVoiceSuffixOverrides(Message):
    class SuffixOverride():
        # __init__
        suffix_type: 'int'  # uint32
        suffix_override: 'int'  # uint32

    # __init__
    suffix_overrides: 'RepeatedCompositeFieldContainer[SetVoiceSuffixOverrides.SuffixOverride]'
    suffix_type: 'int'  # uint32
    suffix_override: 'int'  # uint32


class SetVoiceEffect(Message):
    # __init__
    voice_effect: 'int'  # uint64


class SetPhysique(Message):
    # __init__
    physique: 'str'


class SetFirstName(Message):
    # __init__
    first_name: 'str'


class SetLastName(Message):
    # __init__
    last_name: 'str'


class SetPackedPronouns(Message):
    # __init__
    packed_pronouns: 'str'


class SetBreedName(Message):
    # __init__
    breed_name: 'str'


class SetFullNameKey(Message):
    # __init__
    full_name_key: 'int'  # uint32


class SetFirstNameKey(Message):
    # __init__
    first_name_key: 'int'  # uint32


class SetLastNameKey(Message):
    # __init__
    last_name_key: 'int'  # uint32


class SetPackedPronounsKey(Message):
    # __init__
    packed_pronouns_key: 'int'  # uint32


class SetBreedNameKey(Message):
    # __init__
    breed_name_key: 'int'  # uint32


class SetBusinessNameAndDescriptionKey(Message):
    # __init__
    sim_id: 'int'  # uint64
    name_key: 'int'  # uint32
    description_key: 'int'  # uint32


class SetDynastyNameAndDescriptionKey(Message):
    # __init__
    dynasty_id: 'int'  # uint64
    name_key: 'int'  # uint32
    description_key: 'int'  # uint32


class RouteCancel(Message):
    # __init__
    id: 'int'  # uint64
    orientation: 'Quaternion'
    time: 'float'  # float32


class SetFootprint(Message):
    # __init__
    key: 'ResourceKey'


class UpdateFootprintStatus(Message):
    # __init__
    key: 'ResourceKey'
    enabled: 'bool'


class SetSlot(Message):
    # __init__
    key: 'ResourceKey'


class SetDisabledSlots(Message):
    # __init__
    slots: 'RepeatedCompositeFieldContainer[int]'  # uint32


class SetScale(Message):
    # __init__
    scale: 'float'  # float32


class SetTint(Message):
    # __init__
    tint: 'Vector3'


class SetOpacity(Message):
    # __init__
    opacity: 'float'  # float32


class SetFadeablePartOpacity(Message):
    # __init__
    opacity: 'float'  # float32


class SetPregnancyProgress(Message):
    # __init__
    pregnancy_progress: 'float'  # float32


class SetSinged(Message):
    # __init__
    is_singed: 'bool'


class SetGrubby(Message):
    # __init__
    is_grubby: 'bool'


class SetDyed(Message):
    # __init__
    is_dyed: 'bool'


class SetMessy(Message):
    # __init__
    is_messy: 'bool'


class UpdateSkewerThumbnail(Message):
    # __init__
    sim_id: 'int'  # uint64


class SetTanLevel(Message):
    # __init__
    tan_level: 'int'  # uint32
    outfit_part_data_list: 'RepeatedCompositeFieldContainer[PartData]'
    force_update: 'bool'


class SetGhost(Message):
    # __init__
    is_ghost: 'bool'


class SetGeometryState(Message):
    # __init__
    state_name_hash: 'int'  # uint32


class SetVisibility(Message):
    # __init__
    visibility: 'bool'
    inherits: 'bool'
    enable_drop_shadow: 'bool'


class SetVisibilityFlags(Message):
    # __init__
    visibility_flags: 'int'  # uint32


class SetVisibilityImmediate(Message):
    # __init__
    visibility: 'bool'
    inherits: 'bool'
    enable_drop_shadow: 'bool'


class SetMaterialState(Message):
    # __init__
    state_name_hash: 'int'  # uint32
    opacity: 'float'  # float32
    transition: 'float'  # float32


class SetPinWheelSpinSpeed(Message):
    # __init__
    spin_speed: 'float'  # float32
    transition_speed: 'float'  # float32


class SetSortOrder(Message):
    # __init__
    sort_order: 'int'  # uint32


class SetInteractable(Message):
    # __init__
    interactable: 'bool'


class SetParentType(Message):
    # __init__
    parent_type: 'int'  # uint32
    parent_location: 'int'  # uint64


class SetAudioEffects(Message):
    class AudioEffect():
        # __init__
        key: 'int'  # uint64
        effect_id: 'int'  # uint64
        track_flags: 'int'  # uint32

    # __init__
    audio_effects: 'RepeatedCompositeFieldContainer[SetAudioEffects.AudioEffect]'
    key: 'int'  # uint64
    effect_id: 'int'  # uint64
    track_flags: 'int'  # uint32


class SetActorType(Message):
    # __init__
    actor_type: 'int'  # uint32


class SetActorData(Message):
    # __init__
    type: 'int'  # uint32
    data: 'RepeatedCompositeFieldContainer[int]'  # uint32


class SetActorStateMachineParams(Message):
    class ActorStateMachineParam():
        # __init__
        param_key: 'str'
        param_value_string: 'str'
        param_value_int: 'int'  # uint64
        param_value_bool: 'bool'

    # __init__
    asm_params: 'RepeatedCompositeFieldContainer[SetActorStateMachineParams.ActorStateMachineParam]'
    param_key: 'str'
    param_value_string: 'str'
    param_value_int: 'int'  # uint64
    param_value_bool: 'bool'


class SetFocusScore(Message):
    class FocusScoreEntry():
        # __init__
        base: 'float'  # float64
        multipliers: 'RepeatedCompositeFieldContainer[SetFocusScore.FocusScoreEntry.FocusScoreEntryMultiplier]'
        trait_id: 'int'  # uint64
        multiplier: 'float'  # float64

    class SpecificFocusScoreEntry():
        # __init__
        species: 'int'  # uint32
        score: 'SetFocusScore.FocusScoreEntry'

    # __init__
    global_score: 'SetFocusScore.FocusScoreEntry'
    specific_scores: 'RepeatedCompositeFieldContainer[SetFocusScore.SpecificFocusScoreEntry]'
    base: 'float'  # float64
    multipliers: 'RepeatedCompositeFieldContainer[SetFocusScore.FocusScoreEntry.FocusScoreEntryMultiplier]'
    trait_id: 'int'  # uint64
    multiplier: 'float'  # float64
    species: 'int'  # uint32
    score: 'SetFocusScore.FocusScoreEntry'


class SetSimActive(Message):
    # __init__
    sim_active: 'bool'


class SetSimOutfits(Message):
    # __init__
    outfits: 'OutfitList'


class PartData(Message):
    # __init__
    id: 'int'  # uint64
    body_type: 'int'  # uint32
    color_shift: 'int'  # uint64
    object_id: 'int'  # uint64
    layer_id: 'int'  # uint32


class PartDataListMessage(Message):
    # __init__
    parts: 'RepeatedCompositeFieldContainer[PartData]'


class SetGeneticData(Message):
    # __init__
    sculpts_and_mods_attr: 'bytes'
    physique: 'str'
    voice_pitch: 'float'  # float32
    voice_actor: 'int'  # uint32
    parts_list: 'PartDataListMessage'
    growth_parts_list: 'PartDataListMessage'


class SetThumbnail(Message):
    # __init__
    key: 'ResourceKey'


class VideoSetPlaylist(Message):
    # __init__
    version_id: 'int'  # uint32
    clip_keys: 'RepeatedCompositeFieldContainer[ResourceKey]'
    final_loop: 'bool'
    video_overlay: 'bool'
    mute_speed: 'int'  # uint32
    distortion_speed: 'int'  # uint32
    speed_audio_clip_replacement: 'int'  # uint64
    append_clip: 'bool'


class SetLightDimmer(Message):
    # __init__
    dimmer: 'float'  # float32


class SetLightMaterialStates(Message):
    # __init__
    material_state_on: 'int'  # uint32
    material_state_off: 'int'  # uint32


class SetLightColor(Message):
    # __init__
    color: 'Vector3'


class SetHauntedLight(Message):
    # __init__
    start: 'bool'


class SetCensorState(Message):
    # __init__
    censor_state: 'int'  # uint32


class FadeOpacity(Message):
    # __init__
    duration: 'float'  # float32
    target_value: 'float'  # float32


class SetStandInModel(Message):
    # __init__
    model_key: 'ResourceKey'


class FadeFadeablePartOpacity(Message):
    # __init__
    duration: 'float'  # float32
    target_value: 'float'  # float32


class SetObjectDefStateIndex(Message):
    # __init__
    object_def_state_index: 'int'  # uint32


class SetMoney(Message):
    # __init__
    money: 'int'  # uint32
    reason: 'int'  # uint32
    vfx_amount: 'int'  # int32


class InitializeCollection(Message):
    # __init__
    household_collections: 'RepeatedCompositeFieldContainer[CollectionData]'


class SetPainting(Message):
    # __init__
    painting: 'int'  # uint64
    reveal_level: 'int'  # uint32
    use_overlay: 'bool'
    effect: 'int'  # uint32
    stage_texture_id: 'int'  # uint64
    overlay_texture_id: 'int'  # uint64
    reveal_texture_id: 'int'  # uint64


class SetPuzzle(Message):
    # __init__
    puzzle: 'int'  # uint64
    reveal_level: 'int'  # uint32
    effect: 'int'  # uint32
    overlay_texture_id: 'int'  # uint64
    reveal_texture_id_A: 'int'  # uint64
    reveal_texture_id_B: 'int'  # uint64


class SimPhotoInfo(Message):
    # __init__
    participant_sim_id: 'int'  # fixed uint64
    participant_sim_position: 'Vector3'
    animation_pose: 'AnimationStateRequest'


class TakePhoto(Message):
    class CameraMode(IntEnum):
        FREEFORMPHOTO: 'TakePhoto.CameraMode' = 0
        SIMPHOTO: 'TakePhoto.CameraMode' = 1
        SELFIEPHOTO: 'TakePhoto.CameraMode' = 2
        TWOSIMSELFIEPHOTO: 'TakePhoto.CameraMode' = 3
        PHOTOSTUDIOPHOTO: 'TakePhoto.CameraMode' = 4
        PAINTBYREFERENCE: 'TakePhoto.CameraMode' = 5
        TRIPOD: 'TakePhoto.CameraMode' = 6
        DECORATOR_MODE: 'TakePhoto.CameraMode' = 7
        CROSSSTITCHBYREFERENCE: 'TakePhoto.CameraMode' = 8
        PUZZLEBYREFERENCE: 'TakePhoto.CameraMode' = 9

    FREEFORMPHOTO = CameraMode.FREEFORMPHOTO
    SIMPHOTO = CameraMode.SIMPHOTO
    SELFIEPHOTO = CameraMode.SELFIEPHOTO
    TWOSIMSELFIEPHOTO = CameraMode.TWOSIMSELFIEPHOTO
    PHOTOSTUDIOPHOTO = CameraMode.PHOTOSTUDIOPHOTO
    PAINTBYREFERENCE = CameraMode.PAINTBYREFERENCE
    TRIPOD = CameraMode.TRIPOD
    DECORATOR_MODE = CameraMode.DECORATOR_MODE
    CROSSSTITCHBYREFERENCE = CameraMode.CROSSSTITCHBYREFERENCE
    PUZZLEBYREFERENCE = CameraMode.PUZZLEBYREFERENCE

    class ZoomCapability(IntEnum):
        NONE: 'TakePhoto.ZoomCapability' = 0
        SHORT: 'TakePhoto.ZoomCapability' = 1
        LONG: 'TakePhoto.ZoomCapability' = 2
        VERY_LONG: 'TakePhoto.ZoomCapability' = 3

    NONE = ZoomCapability.NONE
    SHORT = ZoomCapability.SHORT
    LONG = ZoomCapability.LONG
    VERY_LONG = ZoomCapability.VERY_LONG

    class CameraQuality(IntEnum):
        CHEAP: 'TakePhoto.CameraQuality' = 0
        STANDARD: 'TakePhoto.CameraQuality' = 1
        EXPENSIVE: 'TakePhoto.CameraQuality' = 2
        SUPER_EXPENSIVE: 'TakePhoto.CameraQuality' = 3

    CHEAP = CameraQuality.CHEAP
    STANDARD = CameraQuality.STANDARD
    EXPENSIVE = CameraQuality.EXPENSIVE
    SUPER_EXPENSIVE = CameraQuality.SUPER_EXPENSIVE

    class PhotoSize(IntEnum):
        SMALL: 'TakePhoto.PhotoSize' = 0
        MEDIUM: 'TakePhoto.PhotoSize' = 1
        LARGE: 'TakePhoto.PhotoSize' = 2
        EXTRA_LARGE: 'TakePhoto.PhotoSize' = 3

    SMALL = PhotoSize.SMALL
    MEDIUM = PhotoSize.MEDIUM
    LARGE = PhotoSize.LARGE
    EXTRA_LARGE = PhotoSize.EXTRA_LARGE

    class PhotoOrientation(IntEnum):
        LANDSCAPE: 'TakePhoto.PhotoOrientation' = 0
        PORTRAIT: 'TakePhoto.PhotoOrientation' = 1

    LANDSCAPE = PhotoOrientation.LANDSCAPE
    PORTRAIT = PhotoOrientation.PORTRAIT

    class MoodCategory():
        # __init__
        mood_category_up_icon: 'IconInfo'
        mood_category_down_icon: 'IconInfo'
        mood_category_over_icon: 'IconInfo'
        mood_param_values: 'RepeatedCompositeFieldContainer[str]'

    # __init__
    camera_mode: 'TakePhoto.CameraMode'
    zoom_capability: 'TakePhoto.ZoomCapability'
    camera_quality: 'TakePhoto.CameraQuality'
    hide_photographer: 'bool'
    success_chance: 'float'  # float32
    camera_position_bone_name: 'str'
    sim_photo_infos: 'RepeatedCompositeFieldContainer[SimPhotoInfo]'
    filters_disabled: 'bool'
    single_shot_mode: 'bool'
    painting_size: 'TakePhoto.PhotoSize'
    sim_mood_asm_param_name: 'str'
    camera_position_bone_object: 'int'  # fixed uint64
    target_object: 'int'  # fixed uint64
    num_photos_per_session: 'int'  # uint32
    camera_position_offset: 'Vector3'
    rotate_target: 'bool'
    objects_to_hide: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    mood_categories: 'RepeatedCompositeFieldContainer[TakePhoto.MoodCategory]'
    clip_index_values: 'RepeatedCompositeFieldContainer[str]'
    randomize_target_sim_order: 'bool'
    puzzle_size: 'TakePhoto.PhotoSize'
    orientation: 'TakePhoto.PhotoOrientation'
    allow_change_orientation: 'bool'
    allow_change_size: 'bool'
    mood_category_up_icon: 'IconInfo'
    mood_category_down_icon: 'IconInfo'
    mood_category_over_icon: 'IconInfo'
    mood_param_values: 'RepeatedCompositeFieldContainer[str]'


class CompositeParams(Message):
    # __init__
    texture_hash: 'int'  # uint64
    base_scale_x: 'float'  # float32
    base_scale_y: 'float'  # float32
    base_offset_x: 'float'  # float32
    base_offset_y: 'float'  # float32
    overlay_scale_x: 'float'  # float32
    overlay_scale_y: 'float'  # float32
    overlay_offset_x: 'float'  # float32
    overlay_offset_y: 'float'  # float32
    overlay_color: 'Vector3'
    technique: 'int'  # uint32


class CompositeThumbnail(Message):
    # __init__
    thumbnail_url_source: 'str'
    composite_target: 'int'  # uint64
    target_object: 'int'  # fixed uint64
    no_op_version: 'int'  # uint32
    is_modded: 'bool'
    force_rebuild_thumb: 'bool'
    additional_composite_operations: 'RepeatedCompositeFieldContainer[CompositeParams]'


class ObjectThumbnail(Message):
    # __init__
    url: 'str'


class CompositeImages(Message):
    # __init__
    composite_target: 'int'  # uint64
    composite_target_effect: 'int'  # uint64
    target_object: 'int'  # fixed uint64
    additional_composite_operations: 'RepeatedCompositeFieldContainer[CompositeParams]'


class GenerateMemorialPhoto(Message):
    # __init__
    sim_id: 'int'  # uint64


class HouseholdCreate(Message):
    # __init__
    operation_list: 'OperationList'
    money: 'int'  # uint32


class TravelGroupCreate(Message):
    # __init__
    operation_list: 'OperationList'
    zone_id: 'int'  # fixed uint64
    group_type: 'int'  # uint32


class SetValue(Message):
    # __init__
    value: 'int'  # uint32


class SetId(Message):
    # __init__
    id: 'int'  # uint64


class SetBuildBuyUseFlags(Message):
    # __init__
    use_flags: 'int'  # uint32


class SetSimAge(Message):
    # __init__
    age: 'int'  # uint32


class SetSimAgeProgress(Message):
    # __init__
    progress: 'int'  # uint32
    aging_disabled_tooltip: 'LocalizedString'


class SetGender(Message):
    # __init__
    gender: 'int'  # uint32


class SetSpecies(Message):
    # __init__
    species: 'int'  # uint32


class SetDeathType(Message):
    # __init__
    death_type: 'int'  # uint32


class SetCurrentSkillId(Message):
    # __init__
    current_skill_id: 'int'  # uint64


class ChangeSimOutfit(Message):
    # __init__
    type: 'int'  # uint32
    index: 'int'  # uint32


class GigInfo(Message):
    class ObjectiveChain():
        # __init__
        objectives: 'RepeatedCompositeFieldContainer[int]'  # uint64

    # __init__
    gig_type: 'int'  # uint64
    gig_name: 'LocalizedString'
    gig_time: 'int'  # uint64
    gig_icon: 'ResourceKey'
    min_pay: 'int'  # uint32
    max_pay: 'int'  # uint32
    audition_time: 'int'  # uint64
    gig_description: 'LocalizedString'
    aspiration_id: 'int'  # uint64
    customer_id: 'int'  # uint64
    tip_title: 'LocalizedString'
    tip_icon: 'IconInfo'
    additional_objectives: 'RepeatedCompositeFieldContainer[int]'  # uint64
    career_panel_info_text: 'LocalizedString'
    client_preferences: 'RepeatedCompositeFieldContainer[int]'  # uint64
    known_client_preferences: 'RepeatedCompositeFieldContainer[int]'  # uint64
    client_hh_name: 'str'
    client_lot_id: 'int'  # uint64
    budget_spent: 'int'  # int32
    gig_budget: 'int'  # uint32
    use_level_restriction: 'bool'
    level_restriction: 'int'  # int32
    tile_restriction: 'int'  # int32
    gig_end_time: 'int'  # uint64
    gig_uid: 'int'  # uint64
    hide_inactive_objectives: 'bool'
    chained_objectives: 'RepeatedCompositeFieldContainer[GigInfo.ObjectiveChain]'
    objectives: 'RepeatedCompositeFieldContainer[int]'  # uint64


class AuditionUpdate(Message):
    # __init__
    audition_info: 'GigInfo'
    recommended_task: 'IconInfo'


class PreferencesUpdate(Message):
    # __init__
    career_uid: 'int'  # uint64
    revealed_preference_id: 'int'  # uint64
    client_preferences: 'RepeatedCompositeFieldContainer[int]'  # uint64
    known_client_preferences: 'RepeatedCompositeFieldContainer[int]'  # uint64


class SetCareer(Message):
    # __init__
    career_uid: 'int'  # uint64
    career_level: 'int'  # uint32
    performance: 'int'  # int32
    company: 'LocalizedString'
    auto_work: 'bool'
    career_track: 'int'  # uint64
    user_career_level: 'int'  # uint32
    performance_complete: 'bool'
    performance_tooltip: 'LocalizedString'
    skip_next_shift: 'bool'
    is_retired: 'bool'
    paid_time_off_available: 'int'  # uint32
    pay: 'int'  # uint32
    pay_raise_count: 'int'  # uint32
    work_schedule: 'Schedule'
    active_assignments: 'RepeatedCompositeFieldContainer[int]'  # uint64
    paid_time_off_disabled: 'bool'
    gig_info: 'GigInfo'
    schedule_shift_type: 'int'  # uint32
    days_to_enroll: 'int'  # uint32
    enrollment_status: 'int'  # uint32
    additional_description: 'LocalizedString'
    course_skill_name: 'LocalizedString'
    course_description: 'LocalizedString'
    university_career_uid: 'int'  # uint64
    university_uid: 'int'  # uint64
    career_button_tooltip_description: 'LocalizedString'
    preferred_region: 'int'  # uint64
    reputation: 'int'  # int32
    career_display_name_override: 'LocalizedString'
    follow_enabled: 'bool'
    is_active: 'bool'
    workplace_rival_id: 'int'  # uint64
    burnout: 'bool'
    small_business_career_data: 'RepeatedCompositeFieldContainer[SmallBusinessCareerData]'
    enable_infants_tray_button: 'bool'


class VirtualCareerExtraData(Message):
    # __init__
    key: 'str'
    value: 'str'


class VirtualCareer(Message):
    # __init__
    sim_id: 'int'  # fixed uint64
    career_panel_type: 'int'  # uint32
    show_when_no_careers: 'bool'
    extra_data: 'RepeatedCompositeFieldContainer[VirtualCareerExtraData]'


class SetCareers(Message):
    # __init__
    careers: 'RepeatedCompositeFieldContainer[SetCareer]'
    custom_name: 'str'
    custom_description: 'str'
    virtual_careers: 'RepeatedCompositeFieldContainer[VirtualCareer]'


class SmallBusinessCareerData(Message):
    # __init__
    business_name: 'str'
    business_icon: 'ResourceKey'
    owner_id: 'int'  # fixed uint64


class SetAtWorkInfo(Message):
    class AtWorkState(IntEnum):
        WORKDAY_OVER: 'SetAtWorkInfo.AtWorkState' = 0
        WORKDAY_AVAILABLE: 'SetAtWorkInfo.AtWorkState' = 1
        WORKDAY_ATTENDING: 'SetAtWorkInfo.AtWorkState' = 2
        WORKDAY_LATE: 'SetAtWorkInfo.AtWorkState' = 3
        WORKDAY_TIME_OFF: 'SetAtWorkInfo.AtWorkState' = 4
        WORKDAY_ASSIGNMENT: 'SetAtWorkInfo.AtWorkState' = 5
        WORKDAY_ASSIGNMENT_LATE: 'SetAtWorkInfo.AtWorkState' = 6

    WORKDAY_OVER = AtWorkState.WORKDAY_OVER
    WORKDAY_AVAILABLE = AtWorkState.WORKDAY_AVAILABLE
    WORKDAY_ATTENDING = AtWorkState.WORKDAY_ATTENDING
    WORKDAY_LATE = AtWorkState.WORKDAY_LATE
    WORKDAY_TIME_OFF = AtWorkState.WORKDAY_TIME_OFF
    WORKDAY_ASSIGNMENT = AtWorkState.WORKDAY_ASSIGNMENT
    WORKDAY_ASSIGNMENT_LATE = AtWorkState.WORKDAY_ASSIGNMENT_LATE

    # __init__
    career_uid: 'int'  # uint64
    attended_work: 'bool'
    left_work: 'bool'
    work_state: 'SetAtWorkInfo.AtWorkState'
    panel_string: 'LocalizedString'
    tooltip_string: 'LocalizedString'
    end_time_override: 'int'  # uint32
    enable_go_to_work: 'bool'
    enable_go_to_work_early: 'bool'


class DisplayCareerTooltip(Message):
    # __init__
    career_uid: 'int'  # uint64
    sim_id: 'int'  # fixed uint64
    gig_uid: 'int'  # uint64
    objective_uid: 'int'  # uint64


class NotifyNotebookEntryDiscovered(Message):
    # __init__
    subcategory_name: 'LocalizedString'
    sim_id: 'int'  # fixed uint64
    tooltip: 'str'


class SetAtWorkInfos(Message):
    # __init__
    at_work_infos: 'RepeatedCompositeFieldContainer[SetAtWorkInfo]'


class UpdateFindCareerInteractionAvailability(Message):
    # __init__
    enable: 'bool'
    tooltip: 'LocalizedString'


class EndOfWorkdayPromotion(Message):
    # __init__
    text: 'LocalizedString'
    career: 'SetCareer'


class EndOfWorkday(Message):
    # __init__
    career_uid: 'int'  # uint64
    score_text: 'LocalizedString'
    level_icon: 'ResourceKey'
    money_earned: 'int'  # uint32
    paid_time_off_earned: 'int'  # uint32
    promotion: 'EndOfWorkdayPromotion'


class SetSimSleep(Message):
    # __init__
    sleep: 'bool'


class TravelSwitchToZone(Message):
    # __init__
    sim_to_visit_id: 'int'  # uint64
    household_to_control_id: 'int'  # uint64
    zone_id: 'int'  # uint64
    world_id: 'int'  # uint32


class TravelBringToZone(Message):
    # __init__
    sim_to_bring_id: 'int'  # uint64
    household_id: 'int'  # uint64
    zone_id: 'int'  # uint64
    world_id: 'int'  # uint32


class TravelLiveToNhdToLive(Message):
    # __init__
    sim_to_control_id: 'int'  # uint64
    household_to_control_id: 'int'  # uint64
    override_zone_to_load: 'int'  # uint64


class SetPrimaryAspiration(Message):
    # __init__
    aspiration_id: 'int'  # uint64


class SetUnfinishedBusinessAspiration(Message):
    # __init__
    aspiration_id: 'int'  # uint64


class SetSimGameplayFilterFx(Message):
    # __init__
    sim_filter_fx: 'int'  # uint32


class WhimGoal(Message):
    class WhimType(IntEnum):
        UNDEFINED: 'WhimGoal.WhimType' = 0
        LONG_TERM: 'WhimGoal.WhimType' = 1
        SHORT_TERM: 'WhimGoal.WhimType' = 2
        REACTIONARY: 'WhimGoal.WhimType' = 3
        CONFRONTATION: 'WhimGoal.WhimType' = 4

    UNDEFINED = WhimType.UNDEFINED
    LONG_TERM = WhimType.LONG_TERM
    SHORT_TERM = WhimType.SHORT_TERM
    REACTIONARY = WhimType.REACTIONARY
    CONFRONTATION = WhimType.CONFRONTATION

    # __init__
    whim_guid64: 'int'  # uint64
    whim_name: 'LocalizedString'
    whim_score: 'int'  # int32
    whim_noncancel: 'bool'
    whim_icon_key: 'ResourceKey'
    whim_goal_count: 'int'  # uint32
    whim_current_count: 'int'  # uint32
    whim_target_sim: 'int'  # fixed uint64
    whim_tooltip: 'LocalizedString'
    whim_emotional: 'bool'
    whim_tooltip_reason: 'LocalizedString'
    whim_locked: 'bool'
    whim_type: 'WhimGoal.WhimType'
    slot_whim_type: 'WhimGoal.WhimType'
    whim_fluff_text: 'LocalizedString'
    whim_can_lock: 'bool'
    whim_audio_sting_on_complete: 'ResourceKey'


class SetCurrentWhims(Message):
    # __init__
    whim_goals: 'RepeatedCompositeFieldContainer[WhimGoal]'


class SetWhimComplete(Message):
    # __init__
    whim_guid64: 'int'  # uint64


class SetWhimBucks(Message):
    class WhimBuckReason(IntEnum):
        LOAD: 'SetWhimBucks.WhimBuckReason' = 0
        ASPIRATION: 'SetWhimBucks.WhimBuckReason' = 1
        WHIM: 'SetWhimBucks.WhimBuckReason' = 2
        COMMAND: 'SetWhimBucks.WhimBuckReason' = 3
        PURCHASED_REWARD: 'SetWhimBucks.WhimBuckReason' = 4

    LOAD = WhimBuckReason.LOAD
    ASPIRATION = WhimBuckReason.ASPIRATION
    WHIM = WhimBuckReason.WHIM
    COMMAND = WhimBuckReason.COMMAND
    PURCHASED_REWARD = WhimBuckReason.PURCHASED_REWARD

    # __init__
    whim_bucks: 'int'  # uint64
    reason: 'SetWhimBucks.WhimBuckReason'


class SetTraits(Message):
    # __init__
    trait_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    traits_to_add: 'RepeatedCompositeFieldContainer[int]'  # uint64
    traits_to_remove: 'RepeatedCompositeFieldContainer[int]'  # uint64


class ChangeSimAge(Message):
    # __init__
    age: 'int'  # uint32


class SetAccountId(Message):
    # __init__
    account_id: 'int'  # fixed uint64


class SetIsNpc(Message):
    # __init__
    is_npc: 'bool'


class SetPlayerProtectedStatus(Message):
    # __init__
    is_player_protected: 'bool'


class SetPlayedStatus(Message):
    # __init__
    is_played: 'bool'


class SetHouseholdName(Message):
    # __init__
    name: 'str'


class SetHouseholdDescription(Message):
    # __init__
    description: 'str'


class SetHouseholdHidden(Message):
    # __init__
    hidden: 'bool'


class SetHouseholdHomeZoneId(Message):
    # __init__
    home_zone_id: 'int'  # fixed uint64


class SetHouseholdSims(Message):
    # __init__
    sim_ids: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64


class SetRelatedObjects(Message):
    # __init__
    related_object_ids: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    target_sim_id: 'int'  # fixed uint64


class PreloadSimOutfit(Message):
    # __init__
    outfits: 'RepeatedCompositeFieldContainer[OutfitTypeAndIndex]'


class OutfitTypeAndIndex(Message):
    # __init__
    type: 'int'  # uint32
    index: 'int'  # uint32


class SetWallsUpOrDown(Message):
    # __init__
    walls_up: 'bool'
    hide_livable_plexes: 'bool'


class OverrideWallsUp(Message):
    # __init__
    enable_override: 'bool'
    lot_id: 'int'  # uint64


class SetCanLiveDrag(Message):
    # __init__
    can_live_drag: 'bool'


class LiveDragStart(Message):
    # __init__
    live_drag_object_id: 'int'  # fixed uint64
    drag_start_system: 'int'  # uint32
    drop_object_ids: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    stack_id: 'int'  # uint64
    sell_value: 'int'  # int32
    icon_info: 'IconInfo'


class LiveDragEnd(Message):
    # __init__
    live_drag_object_id: 'int'  # fixed uint64
    drag_start_system: 'int'  # uint32
    drag_end_system: 'int'  # uint32
    next_drag_object_id: 'int'  # fixed uint64


class LiveDragCancel(Message):
    # __init__
    live_drag_object_id: 'int'  # fixed uint64
    drag_start_system: 'int'  # uint32
    drag_end_system: 'int'  # uint32


class SetPhoneSilence(Message):
    # __init__
    silence: 'bool'


class SetBabySkinTone(Message):
    # __init__
    cloth_file_name: 'str'
    bassinet_id: 'int'  # fixed uint64


class SetAwayAction(Message):
    # __init__
    icon: 'ResourceKey'
    tooltip: 'LocalizedString'


class SetObjectDefinitionId(Message):
    # __init__
    def_id: 'int'  # uint64


class FocusCamera(Message):
    # __init__
    id: 'int'  # uint64
    location: 'Vector3'
    follow_mode: 'bool'
    position: 'Vector3'


class CancelFocusCamera(Message):
    # __init__
    id: 'int'  # uint64


class FocusCameraOnLot(Message):
    # __init__
    lot_id: 'int'  # uint64
    lerp_time: 'float'  # float32


class SetSimAgeProgressTooltipData(Message):
    # __init__
    current_day: 'int'  # uint32
    ready_to_age_day: 'int'  # uint32
    days_alive: 'int'  # uint32


class MoveHouseholdIntoLotFromGallery(Message):
    # __init__
    zone_id: 'int'  # fixed uint64
    household_id: 'int'  # uint64
    num_household_sims: 'int'  # uint32
    zone_ids: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64


class SetOccultTypes(Message):
    # __init__
    occult_types: 'int'  # uint32


class SetCurrentOccultTypes(Message):
    # __init__
    current_occult_types: 'int'  # uint32


class SetMannequinData(Message):
    # __init__
    sim_info_data: 'MannequinSimData'


class SetMannequinPose(Message):
    # __init__
    animation_pose: 'AnimationStateRequest'


class ShowFamilyTree(Message):
    class FamilyTreeNode():
        # __init__
        sim_id: 'int'  # fixed uint64
        spouse: 'ShowFamilyTree.FamilyTreeNode'
        parents: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        children: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        siblings: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        grandparents: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        grandchildren: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        divorced_spouses: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
        dead_spouses: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'

    # __init__
    root: 'ShowFamilyTree.FamilyTreeNode'
    sim_id: 'int'  # fixed uint64
    spouse: 'ShowFamilyTree.FamilyTreeNode'
    parents: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    children: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    siblings: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    grandparents: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    grandchildren: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    divorced_spouses: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'
    dead_spouses: 'RepeatedCompositeFieldContainer[ShowFamilyTree.FamilyTreeNode]'


class FamilyTreeServiceNode(Message):
    # __init__
    sim_id: 'int'  # fixed uint64
    spouse: 'int'  # fixed uint64
    fiance: 'int'  # fixed uint64
    steady_relationships: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    parents: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    children: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    siblings: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    divorced_spouses: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    dead_spouses: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    bit_id: 'int'  # fixed uint64
    is_adopted: 'bool'
    localized_full_name: 'LocalizedString'
    first_name: 'str'
    last_name: 'str'
    thumbnail_override: 'ResourceKey'
    death_trait_id_override: 'int'  # uint64
    gender: 'int'  # uint32
    sims_connected_by_forgery: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    is_forged: 'bool'
    known_secret_parents: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    known_secret_children: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    dead_kingdom_data: 'FamilyTreeNodeKingdomData'


class DisplayFamilyTree(Message):
    # __init__
    root_id: 'int'  # fixed uint64
    family_nodes: 'RepeatedCompositeFieldContainer[FamilyTreeServiceNode]'


class CustomizableObjectData(Message):
    # __init__
    object_id: 'int'  # fixed uint64
    attributes: 'bytes'
    texture_id: 'int'  # fixed uint64
    material_variant: 'int'  # uint32
    texture_effect: 'int'  # uint32
    parent_id: 'int'  # uint64
    slot_hash: 'int'  # uint32


class CustomizableObjectDataList(Message):
    # __init__
    object_data: 'RepeatedCompositeFieldContainer[CustomizableObjectData]'


class MakeMemoryFromPhoto(Message):
    # __init__
    household_id: 'int'  # uint64
    sim_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    texture_id: 'int'  # uint64
    filter_style: 'int'  # uint32
    favorite: 'bool'
    time_stamp: 'str'


class SetBuckFunds(Message):
    # __init__
    bucks_type: 'int'  # uint32
    available_funds: 'int'  # uint32
    club_id: 'int'  # fixed uint64
    sim_id: 'int'  # fixed uint64


class SetRetailFunds(Message):
    # __init__
    available_funds: 'int'  # int32
    vfx_amount: 'int'  # int32


class SetRetailDailyItemsSold(Message):
    # __init__
    daily_retail_items_sold: 'int'  # uint32


class SetRetailDailyOutgoingCosts(Message):
    # __init__
    daily_retail_outgoing_costs: 'int'  # uint32


class SetRetailDailyNetProfit(Message):
    # __init__
    daily_retail_net_profit: 'int'  # int32


class SetRetailStoreOpen(Message):
    # __init__
    is_open: 'bool'
    time_opened: 'int'  # uint32


class SetAura(Message):
    # __init__
    color: 'Vector3'
    opacity: 'float'  # float32


class SetSimHeadline(Message):
    # __init__
    headline: 'LocalizedString'


class SetLinkedSims(Message):
    # __init__
    linked_sim_ids: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64


class SetMulticolor(Message):
    # __init__
    color: 'RepeatedCompositeFieldContainer[Vector3]'


class SetVFXMask(Message):
    # __init__
    vfx_mask: 'int'  # uint64


class SetExcludeVFXMask(Message):
    # __init__
    exclude_vfx_mask: 'int'  # uint64


class StartEnsemble(Message):
    # __init__
    ensemble_id: 'int'  # uint64


class UpdateEnsemble(Message):
    class UpdateType(IntEnum):
        ADD_MEMBER: 'UpdateEnsemble.UpdateType' = 0
        REMOVE_MEMBER: 'UpdateEnsemble.UpdateType' = 1

    ADD_MEMBER = UpdateType.ADD_MEMBER
    REMOVE_MEMBER = UpdateType.REMOVE_MEMBER

    # __init__
    update_type: 'UpdateEnsemble.UpdateType'
    ensemble_id: 'int'  # uint64
    sim_id: 'int'  # uint64


class EndEnsemble(Message):
    # __init__
    ensemble_id: 'int'  # uint64


class SetDisplayNumber(Message):
    # __init__
    number: 'RepeatedCompositeFieldContainer[int]'  # uint32


class UpdateFlipBook(Message):
    # __init__


class SetOverrideDialogPitch(Message):
    # __init__
    pitch: 'float'  # float32
    override_fast_speed: 'bool'


class InitCameraShake(Message):
    # __init__
    duration: 'float'  # float32
    frequency: 'float'  # float32
    amplitude: 'float'  # float32
    octaves: 'int'  # uint32
    fade_multiplier: 'float'  # float32


class SetCallToAction(Message):
    # __init__
    color: 'Vector3'
    opacity: 'float'  # float32
    speed: 'float'  # float32
    thickness: 'float'  # float32
    tutorial_text: 'LocalizedString'


class SetCallToActionLot(Message):
    # __init__
    zone_id: 'int'  # fixed uint64
    tutorial_text: 'LocalizedString'


class SetScratchedOverlay(Message):
    # __init__
    enabled: 'bool'


class SendHolidayInfo(Message):
    # __init__
    holiday_type: 'int'  # fixed uint64
    name: 'LocalizedString'
    icon: 'ResourceKey'
    time_off_for_work: 'bool'
    time_off_for_school: 'bool'
    traditions: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    max_traditions: 'int'  # uint32
    can_be_modified: 'bool'
    lot_decoration_preset: 'int'  # fixed uint64


class SendActiveHolidayInfo(Message):
    class HolidayUpdateType(IntEnum):
        START: 'SendActiveHolidayInfo.HolidayUpdateType' = 0
        UPDATE: 'SendActiveHolidayInfo.HolidayUpdateType' = 1
        END: 'SendActiveHolidayInfo.HolidayUpdateType' = 2

    START = HolidayUpdateType.START
    UPDATE = HolidayUpdateType.UPDATE
    END = HolidayUpdateType.END

    # __init__
    update_type: 'int'  # uint32
    holiday_type: 'int'  # fixed uint64
    holiday_info: 'SendHolidayInfo'


class SetLotDecorations(Message):
    # __init__
    zone_id: 'int'  # fixed uint64
    holiday_id: 'int'  # fixed uint64
    preset_id: 'int'  # fixed uint64
    fade_in_time: 'float'  # float32
    fade_in_delay: 'float'  # float32
    fade_in_delay_variation: 'float'  # float32


class SetAllowFame(Message):
    # __init__
    allow_fame: 'bool'


class SetAllowReputation(Message):
    # __init__
    allow_reputation: 'bool'


class DisplayHeadline(Message):
    # __init__
    sim_id: 'int'  # uint64
    headline_type: 'int'  # uint64
    value: 'float'  # float32
    icon_modifier: 'ResourceKey'


class OwnedUniversityHousingLoad(Message):
    # __init__
    zone_id: 'int'  # fixed uint64


class SplitHouseholdDialog(Message):
    # __init__
    source_household_id: 'int'  # uint64
    target_household_id: 'int'  # uint64
    cancelable: 'bool'
    allow_sim_transfer: 'bool'
    selected_sim_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    destination_zone_id: 'int'  # uint64
    callback_command_name: 'str'
    lock_preselected_sims: 'bool'


class OrganizationUpdate(Message):
    class OrganizationUpdateType(IntEnum):
        ADD: 'OrganizationUpdate.OrganizationUpdateType' = 0
        UPDATE: 'OrganizationUpdate.OrganizationUpdateType' = 1
        REMOVE: 'OrganizationUpdate.OrganizationUpdateType' = 2

    ADD = OrganizationUpdateType.ADD
    UPDATE = OrganizationUpdateType.UPDATE
    REMOVE = OrganizationUpdateType.REMOVE

    # __init__
    org_id: 'int'  # uint64
    update_type: 'OrganizationUpdate.OrganizationUpdateType'
    objective_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    is_enrolled: 'bool'


class OrganizationEventInfo(Message):
    # __init__
    drama_node_id: 'int'  # uint64
    schedule: 'Schedule'
    event_info: 'IconInfo'
    location: 'LocalizedString'
    zone_id: 'int'  # uint64


class OrganizationEventUpdate(Message):
    # __init__
    org_id: 'int'  # uint64
    events: 'RepeatedCompositeFieldContainer[OrganizationEventInfo]'
    no_events_are_scheduled_string: 'LocalizedString'


class CivicPolicyPanelData(Message):
    # __init__
    voting_open: 'bool'
    repeal_policy_id: 'int'  # uint64
    repeal_policy_sigs: 'int'  # uint32
    schedule_text: 'LocalizedString'


class SendUIMessage(Message):
    # __init__
    message_name: 'str'


class SetTraitAtRiskState(Message):
    # __init__
    trait_id: 'int'  # uint64
    at_risk: 'bool'


class ToggleCustomCamera(Message):
    # __init__
    sim_id: 'int'  # fixed uint64
    camera_on: 'bool'
    camera_mode: 'int'  # uint32


class OpenTutorial(Message):
    # __init__
    tutorial_id: 'int'  # fixed uint64
    source: 'str'


class ClanMembershipUpdate(Message):
    class ClanMembershipUpdateType(IntEnum):
        ADD: 'ClanMembershipUpdate.ClanMembershipUpdateType' = 0
        REMOVE: 'ClanMembershipUpdate.ClanMembershipUpdateType' = 1

    ADD = ClanMembershipUpdateType.ADD
    REMOVE = ClanMembershipUpdateType.REMOVE

    # __init__
    clan_id: 'int'  # uint64
    update_type: 'ClanMembershipUpdate.ClanMembershipUpdateType'


class ClanUpdate(Message):
    # __init__
    clan_leaders: 'RepeatedCompositeFieldContainer[ClanLeaderData]'
    clan_alliance_state: 'int'  # uint32


class TogglePhoneBadge(Message):
    # __init__
    sim_id: 'int'  # uint64
    has_notification: 'bool'


class HorseValueUpdate(Message):
    # __init__
    sim_id: 'int'  # uint64
    value: 'float'  # float32


class ReincarnationCountUpdate(Message):
    # __init__
    sim_id: 'int'  # uint64
    reincarnation_count: 'int'  # uint32


class PivotalCompleted(Message):
    # __init__
    pivotal_moment_id: 'int'  # fixed uint64
    rewarded: 'bool'


class PivotalMomentsItem(Message):
    # __init__
    pivotal_moment_id: 'int'  # fixed uint64
    prereq_id: 'RepeatedCompositeFieldContainer[int]'  # fixed uint64
    day_trigger: 'int'  # uint32
    disabled: 'bool'
    activation_trigger_id: 'int'  # uint32


class PivotalMomentsList(Message):
    # __init__
    completed_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    rewarded_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    items: 'RepeatedCompositeFieldContainer[PivotalMomentsItem]'


class SwitchActiveHouseholdControl(Message):
    # __init__
    sim_id: 'int'  # uint64
    zone_id: 'int'  # fixed uint64
    household_id: 'int'  # uint64
    household_name: 'str'


class RentalUnitManagementData(Message):
    # __init__
    zone_id: 'int'  # fixed uint64
    is_application_process: 'bool'
    house_description_id: 'int'  # fixed uint64
    is_tenant_view: 'bool'
    business_data_update: 'RentalUnitBusinessDataUpdate'
    potential_tenants: 'PotentialTenantApplicationHouseholds'
    remaining_lease: 'int'  # uint32
    npc_property_owner_household_id: 'int'  # uint64


class QuestEvent(Message):
    # __init__
    live_event_id: 'int'  # uint64
    active_pivmos: 'RepeatedCompositeFieldContainer[int]'  # uint64
    cancelable_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    completed_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64
    event_ending: 'bool'


class LiveEventsQuestData(Message):
    # __init__
    quest_event: 'RepeatedCompositeFieldContainer[QuestEvent]'
    active_quests_cap: 'int'  # uint32


class UserAccountData(Message):
    # __init__
    nucleusId: 'int'  # uint64
    data_type: 'int'  # uint32
    data: 'bytes'


class SetGhostColor(Message):
    # __init__
    base_color: 'Vector3'
    edge_color: 'Vector3'


class TriggerUIFlyAway(Message):
    # __init__
    sim_id: 'int'  # uint64
    localizedString: 'LocalizedString'
    keyframeName: 'str'
    spawn_position: 'int'  # uint32


class TraitAppearanceUpdate(Message):
    # __init__
    sim_id: 'int'  # fixed uint64
    trait_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64


class ExperimentNames(Message):
    # __init__
    experiment_names: 'RepeatedCompositeFieldContainer[str]'


class SetPartsCustomTattoos(Message):
    # __init__
    parts_custom_tattoos: 'RepeatedCompositeFieldContainer[SimPartCustomTattooData]'


class SetHouseholdInventoryRewards(Message):
    # __init__
    reward_part_list: 'RewardPartList'


class AncestorData(Message):
    # __init__
    sim_id: 'int'  # uint64
    full_name: 'int'  # uint32
    thumbnail_id: 'ResourceKey'


class SetAncestorsData(Message):
    # __init__
    ancestors: 'RepeatedCompositeFieldContainer[AncestorData]'


class ChildhoodInspirationCompleteStateUpdate(Message):
    # __init__
    sim_id: 'int'  # uint64
    complete_state: 'bool'


class SetResidentList(Message):
    # __init__
    sim_ids: 'RepeatedCompositeFieldContainer[int]'  # uint64


class DynastyInfo(Message):
    class DynastyMessageType(IntEnum):
        ADD: 'DynastyInfo.DynastyMessageType' = 0
        REMOVE: 'DynastyInfo.DynastyMessageType' = 1
        UPDATE: 'DynastyInfo.DynastyMessageType' = 2
        UPDATE_MEMBERS_RANK: 'DynastyInfo.DynastyMessageType' = 3

    ADD = DynastyMessageType.ADD
    REMOVE = DynastyMessageType.REMOVE
    UPDATE = DynastyMessageType.UPDATE
    UPDATE_MEMBERS_RANK = DynastyMessageType.UPDATE_MEMBERS_RANK

    # __init__
    message_type: 'DynastyInfo.DynastyMessageType'
    dynasties: 'RepeatedCompositeFieldContainer[DynastyUIData]'
    active_sim_id: 'int'  # uint64


class KingdomSendAvailableDecrees(Message):
    # __init__
    decrees: 'RepeatedCompositeFieldContainer[KingdomDecree]'
    enacted_decrees: 'RepeatedCompositeFieldContainer[int]'  # uint32


class ScandalSecretInfo(Message):
    class ScandalSecretMessageType(IntEnum):
        ADD: 'ScandalSecretInfo.ScandalSecretMessageType' = 0
        REMOVE: 'ScandalSecretInfo.ScandalSecretMessageType' = 1
        UPDATE: 'ScandalSecretInfo.ScandalSecretMessageType' = 2

    ADD = ScandalSecretMessageType.ADD
    REMOVE = ScandalSecretMessageType.REMOVE
    UPDATE = ScandalSecretMessageType.UPDATE

    class SecretOwnership(IntEnum):
        MY_SECRET: 'ScandalSecretInfo.SecretOwnership' = 0
        OTHERS_SECRET: 'ScandalSecretInfo.SecretOwnership' = 1

    MY_SECRET = SecretOwnership.MY_SECRET
    OTHERS_SECRET = SecretOwnership.OTHERS_SECRET

    # __init__
    message_type: 'ScandalSecretInfo.ScandalSecretMessageType'
    secret_ownership: 'ScandalSecretInfo.SecretOwnership'
    secret_owner_id: 'int'  # fixed uint64
    secret_keeper_id: 'int'  # fixed uint64
    scandal_secret: 'ScandalSecretSimpleData'
